pos(f(adenzelwashington,apakulaalanj)).
pos(f(athomasstielner,akrgnther)).
pos(f(asaromiano,agrimaldiaurelioi)).
pos(f(astefanpetrov,amarinovichanton)).
pos(f(ajuliaroberts,apakulaalanj)).
pos(f(athomasstielner,agutjahrrainer)).
pos(f(agesinecukrowski,astephanbernhard)).
pos(f(anicholaswoodeson,apakulaalanj)).
pos(f(adebraengle,amillergeorgei)).
pos(f(apetardespotov,atraykovatanas)).
pos(f(amarkusbker,aengelhardtwilhelm)).
pos(f(ahorstkummeth,akronthalerthomas)).
pos(f(accilecassel,agustemmanuelii)).
pos(f(ahorstkummeth,akinkelmartin)).
pos(f(asharonstone,acatonjonesmichael)).
pos(f(ahubertmulzer,akinkelmartin)).
pos(f(aandygarcia,asoderberghsteven)).
pos(f(afranoisechristophe,abonnetchristiani)).
pos(f(agesinecukrowski,azensmichael)).
pos(f(akarinthaler,akronthalerthomas)).
pos(f(amarenschumacher,aklischstefan)).
pos(f(ahorstkummeth,akrgnther)).
pos(f(atommikulla,akrgnther)).
pos(f(aeddasabatini,agrimaldiaurelioi)).
pos(f(acharlotterampling,acatonjonesmichael)).
pos(f(ahubertmulzer,akrgnther)).
pos(f(aminianden,asoderberghsteven)).
pos(f(atommikulla,akinkelmartin)).
pos(f(aulrichmhe,astephanbernhard)).
pos(f(athomasstielner,akronthalerthomas)).
pos(f(amarccaleb,amillergeorgei)).
pos(f(amaurizionicolosi,agrimaldiaurelioi)).
pos(f(astevekalfa,atonetticlaudio)).
pos(f(atimberrington,acatonjonesmichael)).
pos(f(astefandanailov,atraykovatanas)).
pos(f(aleonardlansink,astephanbernhard)).
pos(f(asharonstone,averhoevenpauli)).
pos(f(atommikulla,aklischstefan)).
pos(f(apatricejuiff,aapprederisfranck)).
pos(f(aivanbratanov,amarinovichanton)).
pos(f(agabriellelazure,akappesstphane)).
pos(f(adanielvonbargen,averhoevenpauli)).
pos(f(awhoopigoldberg,aaltmanroberti)).
pos(f(afrancishuster,aromeclaudemichel)).
pos(f(athomasstielner,aklischstefan)).
pos(f(araffaeladavi,agrimaldiaurelioi)).
pos(f(avincentlecoeur,aapprederisfranck)).
pos(f(amaxmller,akronthalerthomas)).
pos(f(aconnorwiddows,ametcalfestephen)).
pos(f(atzenokandov,asurchadzhievstefani)).
pos(f(akonstanzebreitebner,astephanbernhard)).
pos(f(aviktordanchenko,asurchadzhievstefani)).
pos(f(aanthonyheald,apakulaalanj)).
pos(f(amaxmller,agutjahrrainer)).
pos(f(akarinthaler,akinkelmartin)).
pos(f(aemiliaradeva,atraykovatanas)).
pos(f(amarksangster,acatonjonesmichael)).
pos(f(awayneknight,averhoevenpauli)).
pos(f(avyarakovacheva,amarinovichanton)).
pos(f(aivangrigorov,atraykovatanas)).
pos(f(aalancpeterson,ametcalfestephen)).
pos(f(acaseyaffleck,asoderberghsteven)).
pos(f(adidierdijoux,aapprederisfranck)).
pos(f(adavidarnett,amillergeorgei)).
pos(f(abruceayoung,averhoevenpauli)).
pos(f(astanleyanderson,apakulaalanj)).
pos(f(adenisarndt,averhoevenpauli)).
pos(f(ahorstkummeth,abraunbettinai)).
pos(f(afranoisechristophe,asummereric)).
pos(f(afrancishuster,aladogedominique)).
pos(f(afrancomirabella,agrimaldiaurelioi)).
pos(f(agerdlohmeyer,akinkelmartin)).
pos(f(adietermann,azensmichael)).
pos(f(aannamariagherardi,abattiatofranco)).
pos(f(aandreasschwaiger,akrgnther)).
pos(f(atheresascholze,astephanbernhard)).
pos(f(afirminerichard,agustemmanuelii)).
pos(f(apatricejuiff,avergnejeanpierre)).
pos(f(astancollymore,acatonjonesmichael)).
pos(f(akarinthaler,agutjahrrainer)).
pos(f(astephentobolowsky,averhoevenpauli)).
pos(f(amaxmller,aklischstefan)).
pos(f(acoralyzahonero,aromeclaudemichel)).
pos(f(avannifois,asciveresmarianna)).
pos(f(athomasstielner,aengelhardtwilhelm)).
pos(f(akarinthaler,aklischstefan)).
pos(f(ajuttawachowiak,azensmichael)).
pos(f(acarmelogalati,asciveresmarianna)).
pos(f(apaolaciampi,agrimaldiaurelioi)).
pos(f(alyubomirbachvarov,apunchevborislav)).
pos(f(aneilmaskell,acatonjonesmichael)).
pos(f(astanleytucci,apakulaalanj)).
pos(f(astevekalfa,abonnetchristiani)).
pos(f(afrancishuster,atonetticlaudio)).
pos(f(afloramontgomery,acatonjonesmichael)).
pos(f(apetergallagher,aaltmanroberti)).
pos(f(abarbaratabita,asciveresmarianna)).
pos(f(ahubertmulzer,abraunbettinai)).
pos(f(astoychomazgalov,apunchevborislav)).
pos(f(aivandimov,amarinovichanton)).
pos(f(astevekalfa,asummereric)).
pos(f(afirminerichard,aladogedominique)).
pos(f(amarisaburger,agutjahrrainer)).
pos(f(afredward,aaltmanroberti)).
pos(f(amarisaburger,akrgnther)).
pos(f(aantoninobruschetta,abattiatofranco)).
pos(f(ajanchappell,acatonjonesmichael)).
pos(f(aeddiejemison,asoderberghsteven)).
pos(f(afirminerichard,atonetticlaudio)).
pos(f(amarenschumacher,akinkelmartin)).
pos(f(anormanarmour,ametcalfestephen)).
pos(f(atommikulla,agutjahrrainer)).
pos(f(avincentlecoeur,avergnejeanpierre)).
pos(f(amarenschumacher,aengelhardtwilhelm)).
pos(f(adillonmoen,ametcalfestephen)).
pos(f(ahubertmulzer,akronthalerthomas)).
pos(f(adidierdijoux,avergnejeanpierre)).
pos(f(atizianalodato,abattiatofranco)).
pos(f(amanueladolcemascolo,asciveresmarianna)).
pos(f(adavidsontag,asoderberghsteven)).
pos(f(amarenschumacher,abraunbettinai)).
pos(f(agerdlohmeyer,aengelhardtwilhelm)).
pos(f(amarcoleonardi,agrimaldiaurelioi)).
pos(f(avolkerranisch,astephanbernhard)).
pos(f(ajuliedray,avergnejeanpierre)).
pos(f(afabiolobello,agrimaldiaurelioi)).
pos(f(amarisaburger,akinkelmartin)).
pos(f(aluciasardo,abattiatofranco)).
pos(f(acoralyzahonero,asummereric)).
pos(f(acarolflorence,asoderberghsteven)).
pos(f(aivantonev,amarinovichanton)).
pos(f(amarenschumacher,akrgnther)).
pos(f(abillyconnolly,ametcalfestephen)).
pos(f(accilecassel,akappesstphane)).
pos(f(abiagiobarone,asciveresmarianna)).
pos(f(aandreasschwaiger,agutjahrrainer)).
pos(f(avincentdonofrio,aaltmanroberti)).
pos(f(aradarassimov,abattiatofranco)).
pos(f(agusmercurio,amillergeorgei)).
pos(f(akostatsonev,atraykovatanas)).
pos(f(adinaconnolly,asoderberghsteven)).
pos(f(afrankpatton,asoderberghsteven)).
pos(f(akarinthaler,akrgnther)).
pos(f(amaxmller,akrgnther)).
pos(f(asamshepard,apakulaalanj)).
pos(f(agerdlohmeyer,agutjahrrainer)).
pos(f(acoralyzahonero,aladogedominique)).
pos(f(akarinthaler,abraunbettinai)).
pos(f(agerdlohmeyer,aklischstefan)).
pos(f(acoralyzahonero,akappesstphane)).
pos(f(aterenceharvey,acatonjonesmichael)).
pos(f(aluciasardo,asciveresmarianna)).
pos(f(ahorstkummeth,aklischstefan)).
pos(f(anicolegrimaudo,abattiatofranco)).
pos(f(ahorstkummeth,agutjahrrainer)).
pos(f(ajorgerhernandez,asoderberghsteven)).
pos(f(ajuliaroberts,asoderberghsteven)).
pos(f(amarkusbker,abraunbettinai)).
pos(f(afrancishuster,asummereric)).
pos(f(aluciasardo,agrimaldiaurelioi)).
pos(f(aivankondov,asurchadzhievstefani)).
pos(f(afrancishuster,agustemmanuelii)).
pos(f(alarrysontag,asoderberghsteven)).
pos(f(afirminerichard,asummereric)).
pos(f(alucavitrano,abattiatofranco)).
pos(f(aguillaumeromain,aapprederisfranck)).
pos(f(aelliottgould,asoderberghsteven)).
pos(f(ahubertmulzer,aengelhardtwilhelm)).
pos(f(aarmelledeutsch,aapprederisfranck)).
pos(f(amikhailmikhajlov,asurchadzhievstefani)).
pos(f(abenjohnson,ametcalfestephen)).
pos(f(ajurneesmollett,ametcalfestephen)).
pos(f(apieradegliesposti,agrimaldiaurelioi)).
pos(f(ajustinmonjo,amillergeorgei)).
pos(f(afirminerichard,abonnetchristiani)).
pos(f(aconsuelolupo,asciveresmarianna)).
pos(f(amarisaburger,akronthalerthomas)).
pos(f(adeanstockwell,aaltmanroberti)).
pos(f(atonygoldwyn,apakulaalanj)).
pos(f(akostatsonev,apunchevborislav)).
pos(f(aangelinasarova,asurchadzhievstefani)).
pos(f(atimothypaulperez,asoderberghsteven)).
pos(f(astefanodionisi,agrimaldiaurelioi)).
pos(f(afranoisechristophe,agustemmanuelii)).
pos(f(aandreasschwaiger,aengelhardtwilhelm)).
pos(f(amarisaburger,abraunbettinai)).
pos(f(adanielegalea,agrimaldiaurelioi)).
pos(f(abrionjames,aaltmanroberti)).
pos(f(ajohnlithgow,apakulaalanj)).
pos(f(agabriellelazure,abonnetchristiani)).
pos(f(arobertculp,apakulaalanj)).
pos(f(agabriellelazure,aromeclaudemichel)).
pos(f(akonstanzebreitebner,azensmichael)).
pos(f(afrankcturner,ametcalfestephen)).
pos(f(aleonardlansink,azensmichael)).
pos(f(acatherinezetajones,asoderberghsteven)).
pos(f(avincenzocrivello,agrimaldiaurelioi)).
pos(f(aceceliaannbirt,asoderberghsteven)).
pos(f(asharonstone,amillergeorgei)).
pos(f(amarkusbker,akrgnther)).
pos(f(awilliamatherton,apakulaalanj)).
pos(f(accilecassel,abonnetchristiani)).
pos(f(ahughkeaysbyrne,amillergeorgei)).
pos(f(ahorstkummeth,aengelhardtwilhelm)).
pos(f(aangelahall,aaltmanroberti)).
pos(f(aclaudiamessner,azensmichael)).
pos(f(afrancishuster,akappesstphane)).
pos(f(anevenakokanova,atraykovatanas)).
pos(f(alylelovett,aaltmanroberti)).
pos(f(amaurolenares,agrimaldiaurelioi)).
pos(f(amarkusbker,aklischstefan)).
pos(f(ahubertmulzer,agutjahrrainer)).
pos(f(aginachiarelli,ametcalfestephen)).
pos(f(amarisaburger,aklischstefan)).
pos(f(accilecassel,aromeclaudemichel)).
pos(f(asharonstone,ametcalfestephen)).
pos(f(amichalbajor,apunchevborislav)).
pos(f(amaxmller,abraunbettinai)).
pos(f(ajuliedray,aapprederisfranck)).
pos(f(ajeannetripplehorn,averhoevenpauli)).
pos(f(agiancarloscuderi,agrimaldiaurelioi)).
pos(f(aloccorbery,aapprederisfranck)).
pos(f(agabrieleferzetti,abattiatofranco)).
pos(f(acoralyzahonero,atonetticlaudio)).
pos(f(ageorgeclooney,asoderberghsteven)).
pos(f(aheathcotewilliams,acatonjonesmichael)).
pos(f(aguillaumeromain,avergnejeanpierre)).
pos(f(amarcospicuglia,agrimaldiaurelioi)).
pos(f(avolkerranisch,azensmichael)).
pos(f(aleahayres,aaltmanroberti)).
pos(f(alaurabetti,agrimaldiaurelioi)).
pos(f(amarenschumacher,agutjahrrainer)).
pos(f(apierrearditi,aapprederisfranck)).
pos(f(abrnicebejo,avergnejeanpierre)).
pos(f(aedkross,asoderberghsteven)).
pos(f(ajrggudzuhn,azensmichael)).
pos(f(aganchoganchev,amarinovichanton)).
pos(f(ajamessikking,apakulaalanj)).
pos(f(atommikulla,aengelhardtwilhelm)).
pos(f(ahristodinev,asurchadzhievstefani)).
pos(f(astoychomazgalov,asurchadzhievstefani)).
pos(f(arichardegrant,aaltmanroberti)).
pos(f(adannflorek,ametcalfestephen)).
pos(f(afirminerichard,aromeclaudemichel)).
pos(f(atzvetolyubrakovski,amarinovichanton)).
pos(f(aludwigbriand,avergnejeanpierre)).
pos(f(aluciacammalleri,asciveresmarianna)).
pos(f(aloccorbery,avergnejeanpierre)).
pos(f(agerdlohmeyer,abraunbettinai)).
pos(f(adonatellafinocchiaro,abattiatofranco)).
pos(f(ajohnfinn,apakulaalanj)).
pos(f(aannejacques,asoderberghsteven)).
pos(f(aandreasschwaiger,akinkelmartin)).
pos(f(asavahashamov,asurchadzhievstefani)).
pos(f(asonyadjulgerova,atraykovatanas)).
pos(f(apierrearditi,avergnejeanpierre)).
pos(f(asydneypollack,aaltmanroberti)).
pos(f(aalexandrawinisky,aapprederisfranck)).
pos(f(amarkusbker,akinkelmartin)).
pos(f(amanliosgalambro,abattiatofranco)).
pos(f(ajannowicki,apunchevborislav)).
pos(f(amariashopova,amarinovichanton)).
pos(f(acaitlinoheaney,amillergeorgei)).
pos(f(ahubertmulzer,aklischstefan)).
pos(f(aantonradichev,apunchevborislav)).
pos(f(ageorgistamatov,amarinovichanton)).
pos(f(amichaeldouglas,averhoevenpauli)).
pos(f(aianholm,ametcalfestephen)).
pos(f(alorigalinski,asoderberghsteven)).
pos(f(aellenthomas,acatonjonesmichael)).
pos(f(ahumecronyn,apakulaalanj)).
pos(f(abrigittefossey,avergnejeanpierre)).
pos(f(abradpitt,asoderberghsteven)).
pos(f(astevekalfa,aladogedominique)).
pos(f(aindiravarma,acatonjonesmichael)).
pos(f(agerdlohmeyer,akronthalerthomas)).
pos(f(atommikulla,akronthalerthomas)).
pos(f(arobyndouglass,amillergeorgei)).
pos(f(achelcieross,averhoevenpauli)).
pos(f(agabriellelazure,aladogedominique)).
pos(f(adimitarhadzhiyanev,atraykovatanas)).
pos(f(agabriellelazure,agustemmanuelii)).
pos(f(afranoisechristophe,atonetticlaudio)).
pos(f(ahughdancy,acatonjonesmichael)).
pos(f(atommikulla,abraunbettinai)).
pos(f(akarinthaler,aengelhardtwilhelm)).
pos(f(agerdlohmeyer,akrgnther)).
pos(f(aandreasschwaiger,aklischstefan)).
pos(f(aauroraquattrocchi,agrimaldiaurelioi)).
pos(f(adietermann,astephanbernhard)).
pos(f(aandreasschwaiger,akronthalerthomas)).
pos(f(agabriellelazure,atonetticlaudio)).
pos(f(amaxmller,aengelhardtwilhelm)).
pos(f(accilecassel,asummereric)).
pos(f(asamantharnier,aapprederisfranck)).
pos(f(accilecassel,atonetticlaudio)).
pos(f(amarkusbker,agutjahrrainer)).
pos(f(acoralyzahonero,abonnetchristiani)).
pos(f(ajackmcgee,averhoevenpauli)).
pos(f(atheresascholze,azensmichael)).
pos(f(agabriellelazure,asummereric)).
pos(f(apaullnolan,asoderberghsteven)).
pos(f(adavidmorrissey,acatonjonesmichael)).
pos(f(alyubomirbobchevski,asurchadzhievstefani)).
pos(f(atimrobbins,aaltmanroberti)).
neg(f(afabiolobello,asurchadzhievstefani)).
neg(f(araffaeladavi,agutjahrrainer)).
neg(f(afloramontgomery,asciveresmarianna)).
neg(f(ageorgedzundza,apakulaalanj)).
neg(f(asotirmaynolovski,agrimaldiaurelioi)).
neg(f(alewissmith,averhoevenpauli)).
neg(f(abrnicebejo,amarinovichanton)).
neg(f(amarkgantt,abonnetchristiani)).
neg(f(amanueladolcemascolo,avergnejeanpierre)).
neg(f(agusmercurio,akappesstphane)).
neg(f(acarmelogalati,asoderberghsteven)).
neg(f(aenzodimartino,abraunbettinai)).
neg(f(aivandimov,agutjahrrainer)).
neg(f(asalvatorelazzaro,asciveresmarianna)).
neg(f(apieradegliesposti,aladogedominique)).
neg(f(aanthonyheald,akrgnther)).
neg(f(achelcieross,aromeclaudemichel)).
neg(f(astevekuhn,abraunbettinai)).
neg(f(apetyasilyanova,akappesstphane)).
neg(f(ahubertmulzer,amarinovichanton)).
neg(f(ahughdancy,atonetticlaudio)).
neg(f(ajamessikking,apunchevborislav)).
neg(f(agesinecukrowski,agrimaldiaurelioi)).
neg(f(aceceliaannbirt,akinkelmartin)).
neg(f(agerdlohmeyer,averhoevenpauli)).
neg(f(alorigalinski,akronthalerthomas)).
neg(f(aulrichmhe,asummereric)).
neg(f(aviktordanchenko,azensmichael)).
neg(f(acesareapolito,apunchevborislav)).
neg(f(alylelovett,abonnetchristiani)).
neg(f(ahorstkummeth,asciveresmarianna)).
neg(f(ajohnlithgow,aladogedominique)).
neg(f(ajuliedray,agutjahrrainer)).
neg(f(abillyconnolly,abattiatofranco)).
neg(f(arobyndouglass,atraykovatanas)).
neg(f(aestefanacastro,azensmichael)).
neg(f(ascottcaan,aromeclaudemichel)).
neg(f(arobertculp,abonnetchristiani)).
neg(f(apenlopecruz,acatonjonesmichael)).
neg(f(ahristodinev,aladogedominique)).
neg(f(adenisarndt,asurchadzhievstefani)).
neg(f(arobertculp,agustemmanuelii)).
neg(f(acaitlinoheaney,apunchevborislav)).
neg(f(ajohnheard,asoderberghsteven)).
neg(f(adenisarndt,asciveresmarianna)).
neg(f(abrnicebejo,akrgnther)).
neg(f(ahorstkummeth,atonetticlaudio)).
neg(f(ajustinmonjo,atonetticlaudio)).
neg(f(adavidarnett,atonetticlaudio)).
neg(f(apieradegliesposti,azensmichael)).
neg(f(avannifois,aromeclaudemichel)).
neg(f(asaromiano,atonetticlaudio)).
neg(f(astefanpetrov,asummereric)).
neg(f(ageorgedzundza,amarinovichanton)).
neg(f(asaromiano,azensmichael)).
neg(f(aginachiarelli,abraunbettinai)).
neg(f(apatricejuiff,asummereric)).
neg(f(agusmercurio,acatonjonesmichael)).
neg(f(anicholaswoodeson,abraunbettinai)).
neg(f(aivantonev,aklischstefan)).
neg(f(avyarakovacheva,astephanbernhard)).
neg(f(akunkabaeva,agutjahrrainer)).
neg(f(adannflorek,abonnetchristiani)).
neg(f(avincentdonofrio,ametcalfestephen)).
neg(f(aivankondov,atonetticlaudio)).
neg(f(asaromiano,averhoevenpauli)).
neg(f(asotirmaynolovski,apakulaalanj)).
neg(f(amiguelferrer,aengelhardtwilhelm)).
neg(f(avannifois,aladogedominique)).
neg(f(agretascacchi,akappesstphane)).
neg(f(amarcocavicchioli,asummereric)).
neg(f(athomasstielner,apunchevborislav)).
neg(f(astoychomazgalov,abraunbettinai)).
neg(f(astancollymore,azensmichael)).
neg(f(abrnicebejo,averhoevenpauli)).
neg(f(adavidsontag,aromeclaudemichel)).
neg(f(aeddasabatini,amarinovichanton)).
neg(f(aganchoganchev,aengelhardtwilhelm)).
neg(f(arichardegrant,agutjahrrainer)).
neg(f(asalvatorelazzaro,akronthalerthomas)).
neg(f(ajanchappell,amillergeorgei)).
neg(f(ascottcaan,apunchevborislav)).
neg(f(ahumecronyn,asoderberghsteven)).
neg(f(amichalbajor,akronthalerthomas)).
neg(f(acaitlinoheaney,agustemmanuelii)).
neg(f(abenjohnson,avergnejeanpierre)).
neg(f(abenjaminmouton,avergnejeanpierre)).
neg(f(aalancpeterson,abraunbettinai)).
neg(f(abruceayoung,akronthalerthomas)).
neg(f(aangelinasarova,aromeclaudemichel)).
neg(f(anormanarmour,abonnetchristiani)).
neg(f(achelcieross,asoderberghsteven)).
neg(f(ajohnfinn,aklischstefan)).
neg(f(anelsonpeltz,aengelhardtwilhelm)).
neg(f(acarmelogalati,azensmichael)).
neg(f(afirminerichard,acatonjonesmichael)).
neg(f(aleonardlansink,avergnejeanpierre)).
neg(f(astefandanailov,avergnejeanpierre)).
neg(f(atommikulla,atonetticlaudio)).
neg(f(aivankondov,avergnejeanpierre)).
neg(f(aivanbratanov,agrimaldiaurelioi)).
neg(f(asamantharnier,aromeclaudemichel)).
neg(f(adanielvonbargen,aklischstefan)).
neg(f(aellenthomas,asoderberghsteven)).
neg(f(arenateschroeter,asciveresmarianna)).
neg(f(amiguelferrer,agustemmanuelii)).
neg(f(astefandanailov,akinkelmartin)).
neg(f(astefanodionisi,akinkelmartin)).
neg(f(aeddasabatini,amillergeorgei)).
neg(f(avincenzocrivello,abattiatofranco)).
neg(f(adanielegalea,akinkelmartin)).
neg(f(ajohnheard,asurchadzhievstefani)).
neg(f(amariashopova,aapprederisfranck)).
neg(f(acynthiastevenson,akappesstphane)).
neg(f(aangelinasarova,amillergeorgei)).
neg(f(abenjaminmouton,azensmichael)).
neg(f(alorigalinski,agustemmanuelii)).
neg(f(atommikulla,avergnejeanpierre)).
neg(f(alaurabetti,akronthalerthomas)).
neg(f(abillcable,agustemmanuelii)).
neg(f(adinamerrill,amarinovichanton)).
neg(f(araffaeladavi,astephanbernhard)).
neg(f(ajuttawachowiak,atraykovatanas)).
neg(f(amarcocavicchioli,akrgnther)).
neg(f(alorigalinski,abraunbettinai)).
neg(f(abenjaminmouton,atonetticlaudio)).
neg(f(acorradofortuna,aladogedominique)).
neg(f(astefanpetrov,amillergeorgei)).
neg(f(aleonardlansink,acatonjonesmichael)).
neg(f(abillyconnolly,abraunbettinai)).
neg(f(ahughkeaysbyrne,abonnetchristiani)).
neg(f(akirilyanev,aapprederisfranck)).
neg(f(aindiravarma,aaltmanroberti)).
neg(f(amarcocavicchioli,asoderberghsteven)).
neg(f(ajamessikking,astephanbernhard)).
neg(f(acesareapolito,aklischstefan)).
neg(f(amiguelferrer,asciveresmarianna)).
neg(f(araffaeladavi,abraunbettinai)).
neg(f(amiguelferrer,aapprederisfranck)).
neg(f(adimitarhadzhiyanev,aengelhardtwilhelm)).
neg(f(acynthiastevenson,abonnetchristiani)).
neg(f(aviktordanchenko,amarinovichanton)).
neg(f(apieradegliesposti,agustemmanuelii)).
neg(f(aloccorbery,asoderberghsteven)).
neg(f(aivanbratanov,atraykovatanas)).
neg(f(apetergallagher,aladogedominique)).
neg(f(aemiliaradeva,aengelhardtwilhelm)).
neg(f(alylelovett,agutjahrrainer)).
neg(f(ajackmcgee,abattiatofranco)).
neg(f(amarccaleb,agrimaldiaurelioi)).
neg(f(apetyasilyanova,amillergeorgei)).
neg(f(aangelahall,akrgnther)).
neg(f(alarrysontag,akappesstphane)).
neg(f(amikhailmikhajlov,atonetticlaudio)).
neg(f(alyubomirbobchevski,abonnetchristiani)).
neg(f(asheilapaterson,abattiatofranco)).
neg(f(aannejacques,acatonjonesmichael)).
neg(f(arichardegrant,avergnejeanpierre)).
neg(f(amiguelferrer,abraunbettinai)).
neg(f(amaurolenares,amarinovichanton)).
neg(f(anormanarmour,asoderberghsteven)).
neg(f(acesareapolito,agutjahrrainer)).
neg(f(adillonmoen,acatonjonesmichael)).
neg(f(astoychomazgalov,atonetticlaudio)).
neg(f(anormanarmour,amillergeorgei)).
neg(f(arobyndouglass,asciveresmarianna)).
neg(f(amarenschumacher,abattiatofranco)).
neg(f(adanielvonbargen,atonetticlaudio)).
neg(f(acoralyzahonero,astephanbernhard)).
neg(f(afloramontgomery,akronthalerthomas)).
neg(f(aconnorwiddows,azensmichael)).
neg(f(apetergallagher,aklischstefan)).
neg(f(afrankcturner,aengelhardtwilhelm)).
neg(f(aberniemac,acatonjonesmichael)).
neg(f(acharlotterampling,agutjahrrainer)).
neg(f(aedkross,agrimaldiaurelioi)).
neg(f(astoychomazgalov,ametcalfestephen)).
neg(f(aulrichmhe,asurchadzhievstefani)).
neg(f(amaurizionicolosi,astephanbernhard)).
neg(f(adonatellafinocchiaro,agutjahrrainer)).
neg(f(avolkerranisch,avergnejeanpierre)).
neg(f(alewissmith,aapprederisfranck)).
neg(f(aivandimov,asciveresmarianna)).
neg(f(arenateschroeter,asummereric)).
neg(f(agabrieleferzetti,atonetticlaudio)).
neg(f(araffaeladavi,agustemmanuelii)).
neg(f(amarcospicuglia,aladogedominique)).
neg(f(aalancpeterson,aladogedominique)).
neg(f(aneilmaskell,ametcalfestephen)).
neg(f(amichaeldouglas,aapprederisfranck)).
neg(f(aclaudiamessner,aklischstefan)).
neg(f(apaullnolan,acatonjonesmichael)).
neg(f(aserenaautieri,apakulaalanj)).
neg(f(avincenzocrivello,asoderberghsteven)).
neg(f(ascottcaan,aklischstefan)).
neg(f(astanleytucci,ametcalfestephen)).
neg(f(aandygarcia,avergnejeanpierre)).
neg(f(aemiliaradeva,asciveresmarianna)).
neg(f(arobyndouglass,amarinovichanton)).
neg(f(adanielegalea,asummereric)).
neg(f(afrankpatton,asummereric)).
neg(f(aivantonev,atraykovatanas)).
neg(f(adorothymalone,apunchevborislav)).
neg(f(amarenschumacher,agrimaldiaurelioi)).
neg(f(ajannowicki,agrimaldiaurelioi)).
neg(f(asalvatorelazzaro,agustemmanuelii)).
neg(f(aivangrigorov,abattiatofranco)).
neg(f(awayneknight,asoderberghsteven)).
neg(f(akonstanzebreitebner,apakulaalanj)).
neg(f(agilbellows,aklischstefan)).
neg(f(acaitlinoheaney,aengelhardtwilhelm)).
neg(f(amaxmller,asurchadzhievstefani)).
neg(f(aantoninobruschetta,agutjahrrainer)).
neg(f(abiagiobarone,akronthalerthomas)).
neg(f(aellenthomas,averhoevenpauli)).
neg(f(aannamariagherardi,amarinovichanton)).
neg(f(abenjohnson,atonetticlaudio)).
neg(f(aheathcotewilliams,abattiatofranco)).
neg(f(alyubomirbachvarov,amarinovichanton)).
neg(f(aandygarcia,abattiatofranco)).
neg(f(aenzodimartino,asciveresmarianna)).
neg(f(afloramontgomery,astephanbernhard)).
neg(f(astoychomazgalov,asciveresmarianna)).
neg(f(aeddiejemison,asurchadzhievstefani)).
neg(f(afredward,aapprederisfranck)).
neg(f(afrankpatton,akinkelmartin)).
neg(f(amikhailmikhajlov,averhoevenpauli)).
neg(f(abillcable,asciveresmarianna)).
neg(f(aulrichmhe,amillergeorgei)).
neg(f(avincentdonofrio,abattiatofranco)).
neg(f(adanielegalea,asciveresmarianna)).
neg(f(abrnicebejo,apakulaalanj)).
neg(f(abrionjames,apakulaalanj)).
neg(f(aarmelledeutsch,agutjahrrainer)).
neg(f(amarkgantt,agrimaldiaurelioi)).
neg(f(awilliamatherton,akappesstphane)).
neg(f(adeanstockwell,akinkelmartin)).
neg(f(avincenzocrivello,avergnejeanpierre)).
neg(f(amichaeldouglas,asoderberghsteven)).
neg(f(acaseyaffleck,agrimaldiaurelioi)).
neg(f(alaurabetti,abattiatofranco)).
neg(f(aenzodimartino,apakulaalanj)).
neg(f(aalancpeterson,aromeclaudemichel)).
neg(f(asydneypollack,abonnetchristiani)).
neg(f(anicholaswoodeson,azensmichael)).
neg(f(adietermann,aromeclaudemichel)).
neg(f(amarcospicuglia,aromeclaudemichel)).
neg(f(aclaudiamessner,aaltmanroberti)).
neg(f(awhoopigoldberg,aklischstefan)).
neg(f(amikhailmikhajlov,aladogedominique)).
neg(f(asavahashamov,abonnetchristiani)).
neg(f(avolkerranisch,agustemmanuelii)).
neg(f(abillcable,amarinovichanton)).
neg(f(astanleytucci,azensmichael)).
neg(f(abillcable,aladogedominique)).
neg(f(agabriellelazure,acatonjonesmichael)).
neg(f(aemilmarkov,akronthalerthomas)).
neg(f(alucavitrano,aromeclaudemichel)).
neg(f(abradpitt,astephanbernhard)).
neg(f(ahughdancy,asciveresmarianna)).
neg(f(afrankpatton,amillergeorgei)).
neg(f(amarksangster,astephanbernhard)).
neg(f(ajackmcgee,aklischstefan)).
neg(f(aedkross,asciveresmarianna)).
neg(f(aeddasabatini,asurchadzhievstefani)).
neg(f(awilliamatherton,atraykovatanas)).
neg(f(abenjaminmouton,akronthalerthomas)).
neg(f(akirilyanev,acatonjonesmichael)).
neg(f(aivanbratanov,apunchevborislav)).
neg(f(amaurizionicolosi,aaltmanroberti)).
neg(f(atimberrington,akrgnther)).
neg(f(aviktordanchenko,agutjahrrainer)).
neg(f(aantoninobruschetta,astephanbernhard)).
neg(f(araffaeladavi,azensmichael)).
neg(f(avannifois,agutjahrrainer)).
neg(f(apenlopecruz,agustemmanuelii)).
neg(f(atzvetolyubrakovski,azensmichael)).
neg(f(aberniemac,aapprederisfranck)).
neg(f(astefanpejchev,aklischstefan)).
neg(f(amichaeldouglas,aaltmanroberti)).
neg(f(awhoopigoldberg,aapprederisfranck)).
neg(f(amaxmller,apunchevborislav)).
neg(f(avincenzocrivello,averhoevenpauli)).
neg(f(abiagiobarone,agutjahrrainer)).
neg(f(aestefanacastro,asciveresmarianna)).
neg(f(amarcospicuglia,azensmichael)).
neg(f(apierrearditi,akrgnther)).
neg(f(afrancomirabella,aklischstefan)).
neg(f(alloydalan,astephanbernhard)).
neg(f(aradarassimov,agrimaldiaurelioi)).
neg(f(aserenaautieri,abonnetchristiani)).
neg(f(ageorgedzundza,aapprederisfranck)).
neg(f(agilbellows,abraunbettinai)).
neg(f(astevekuhn,avergnejeanpierre)).
neg(f(arobyndouglass,agustemmanuelii)).
neg(f(asotirmaynolovski,amarinovichanton)).
neg(f(afrankpatton,azensmichael)).
neg(f(aellenthomas,amillergeorgei)).
neg(f(apetardespotov,apunchevborislav)).
neg(f(atizianalodato,abraunbettinai)).
neg(f(aanthonyheald,agutjahrrainer)).
neg(f(aulrichmhe,apunchevborislav)).
neg(f(ajurneesmollett,acatonjonesmichael)).
neg(f(akonstanzebreitebner,agrimaldiaurelioi)).
neg(f(aangelinasarova,astephanbernhard)).
neg(f(agusmercurio,aaltmanroberti)).
neg(f(abrigittefossey,aladogedominique)).
neg(f(astefanpejchev,aromeclaudemichel)).
neg(f(aianholm,amillergeorgei)).
neg(f(alylelovett,agustemmanuelii)).
neg(f(apaolaciampi,agustemmanuelii)).
neg(f(agabriellelazure,apunchevborislav)).
neg(f(atimberrington,atonetticlaudio)).
neg(f(aberniemac,azensmichael)).
neg(f(abogomilsimeonov,asoderberghsteven)).
neg(f(amanueladolcemascolo,aladogedominique)).
neg(f(acarolflorence,abraunbettinai)).
neg(f(aestefanacastro,amillergeorgei)).
neg(f(aceceliaannbirt,agrimaldiaurelioi)).
neg(f(amarkgantt,atraykovatanas)).
neg(f(afrancomirabella,asciveresmarianna)).
neg(f(abogomilsimeonov,abonnetchristiani)).
neg(f(asydneypollack,apunchevborislav)).
neg(f(ajurneesmollett,asurchadzhievstefani)).
neg(f(aianholm,aromeclaudemichel)).
neg(f(alewissmith,akappesstphane)).
neg(f(akarinthaler,asummereric)).
neg(f(aluciasardo,atonetticlaudio)).
neg(f(agiancarloscuderi,asummereric)).
neg(f(arobertculp,abraunbettinai)).
neg(f(abradpitt,aklischstefan)).
neg(f(aalicjajachiewicz,aapprederisfranck)).
neg(f(adeanstockwell,aklischstefan)).
neg(f(amaurolenares,acatonjonesmichael)).
neg(f(ajohnheard,abraunbettinai)).
neg(f(aulrichmhe,agutjahrrainer)).
neg(f(adidierdijoux,asoderberghsteven)).
neg(f(atizianalodato,aapprederisfranck)).
neg(f(aangelahall,acatonjonesmichael)).
neg(f(asheilapaterson,acatonjonesmichael)).
neg(f(amarcoleonardi,asurchadzhievstefani)).
neg(f(aalicjajachiewicz,asciveresmarianna)).
neg(f(agerdlohmeyer,asciveresmarianna)).
neg(f(akarinthaler,asoderberghsteven)).
neg(f(apieradegliesposti,atonetticlaudio)).
neg(f(aileanarigano,agustemmanuelii)).
neg(f(arobertculp,asciveresmarianna)).
neg(f(amanliosgalambro,akappesstphane)).
neg(f(adavidthewlis,akinkelmartin)).
neg(f(asonyadjulgerova,asoderberghsteven)).
neg(f(amarksangster,abraunbettinai)).
neg(f(afrancomirabella,asoderberghsteven)).
neg(f(akirilyanev,ametcalfestephen)).
neg(f(apierrearditi,aengelhardtwilhelm)).
neg(f(aalicjajachiewicz,ametcalfestephen)).
neg(f(adavidthewlis,aengelhardtwilhelm)).
neg(f(anelsonpeltz,aaltmanroberti)).
neg(f(apierrearditi,agustemmanuelii)).
neg(f(asydneypollack,asoderberghsteven)).
neg(f(aloccorbery,aromeclaudemichel)).
neg(f(astefanodionisi,aladogedominique)).
neg(f(apenlopecruz,ametcalfestephen)).
neg(f(aconnorwiddows,akinkelmartin)).
neg(f(aauroraquattrocchi,azensmichael)).
neg(f(avincentlecoeur,apunchevborislav)).
neg(f(ajuliaroberts,abattiatofranco)).
neg(f(athomasstielner,agrimaldiaurelioi)).
neg(f(aeddiejemison,aaltmanroberti)).
neg(f(aivankondov,asummereric)).
neg(f(aguillaumeromain,averhoevenpauli)).
neg(f(astephentobolowsky,amarinovichanton)).
neg(f(aleilanisarelle,avergnejeanpierre)).
neg(f(alylelovett,atonetticlaudio)).
neg(f(aconnorwiddows,asurchadzhievstefani)).
neg(f(ajuttawachowiak,aladogedominique)).
neg(f(apatricejuiff,aromeclaudemichel)).
neg(f(alarrysontag,averhoevenpauli)).
neg(f(aanthonyheald,aapprederisfranck)).
neg(f(astancollymore,asummereric)).
neg(f(alewissmith,asoderberghsteven)).
neg(f(adavidsontag,abraunbettinai)).
neg(f(apetyasilyanova,asoderberghsteven)).
neg(f(avincenzocrivello,akappesstphane)).
neg(f(adimitarhadzhiyanev,akappesstphane)).
neg(f(alyubomirkanev,ametcalfestephen)).
neg(f(amarkgantt,asummereric)).
neg(f(avincentlecoeur,asurchadzhievstefani)).
neg(f(acatherinezetajones,abonnetchristiani)).
neg(f(aandygarcia,agustemmanuelii)).
neg(f(aclaudiamessner,atraykovatanas)).
neg(f(ajuliedray,abonnetchristiani)).
neg(f(afranoisechristophe,abattiatofranco)).
neg(f(atizianalodato,azensmichael)).
neg(f(abrionjames,atraykovatanas)).
neg(f(aantoniettacarbonetti,aapprederisfranck)).
neg(f(arenateschroeter,akappesstphane)).
neg(f(amariashopova,apunchevborislav)).
neg(f(aalicjajachiewicz,aaltmanroberti)).
neg(f(ahristodinev,abraunbettinai)).
neg(f(amariashopova,akappesstphane)).
neg(f(asotirmaynolovski,acatonjonesmichael)).
neg(f(aandygarcia,abraunbettinai)).
neg(f(akunkabaeva,atraykovatanas)).
neg(f(adeanstockwell,asoderberghsteven)).
neg(f(aenzodimartino,asummereric)).
neg(f(apatricejuiff,azensmichael)).
neg(f(akirilyanev,amillergeorgei)).
neg(f(amikhailmikhajlov,amillergeorgei)).
neg(f(anormanarmour,akrgnther)).
neg(f(aangelahall,agutjahrrainer)).
neg(f(astanleyanderson,asummereric)).
neg(f(agilbellows,acatonjonesmichael)).
neg(f(aangelahall,ametcalfestephen)).
neg(f(amikhailmikhajlov,akrgnther)).
neg(f(amarcocavicchioli,averhoevenpauli)).
neg(f(aemilmarkov,abraunbettinai)).
neg(f(ajohnlithgow,abattiatofranco)).
neg(f(abenjaminmouton,amarinovichanton)).
neg(f(asamantharnier,agrimaldiaurelioi)).
neg(f(amarccaleb,akinkelmartin)).
neg(f(atommikulla,agustemmanuelii)).
neg(f(amanueladolcemascolo,asummereric)).
neg(f(aivantonev,azensmichael)).
neg(f(avincentdonofrio,amillergeorgei)).
neg(f(amikhailmikhajlov,amarinovichanton)).
neg(f(aemilmarkov,amillergeorgei)).
neg(f(ajuliedray,acatonjonesmichael)).
neg(f(apaullnolan,atonetticlaudio)).
neg(f(ajackmcgee,abonnetchristiani)).
neg(f(amaurizionicolosi,akronthalerthomas)).
neg(f(aarmelledeutsch,abraunbettinai)).
neg(f(aantonradichev,astephanbernhard)).
neg(f(afrankpatton,asurchadzhievstefani)).
neg(f(adavidarnett,atraykovatanas)).
neg(f(adavidmorrissey,abonnetchristiani)).
neg(f(acoralyzahonero,apakulaalanj)).
neg(f(aannamariagherardi,asurchadzhievstefani)).
neg(f(apaolaciampi,avergnejeanpierre)).
neg(f(arichardegrant,akronthalerthomas)).
neg(f(apieradegliesposti,abonnetchristiani)).
neg(f(adenisarndt,ametcalfestephen)).
neg(f(amariashopova,asoderberghsteven)).
neg(f(aivangrigorov,aladogedominique)).
neg(f(alucavitrano,aladogedominique)).
neg(f(amarcoleonardi,aaltmanroberti)).
neg(f(awhoopigoldberg,abonnetchristiani)).
neg(f(amaurizionicolosi,akrgnther)).
neg(f(astanleytucci,averhoevenpauli)).
neg(f(aterenceharvey,aaltmanroberti)).
neg(f(aradarassimov,aromeclaudemichel)).
neg(f(amarksangster,asciveresmarianna)).
neg(f(aradarassimov,amarinovichanton)).
neg(f(aarmelledeutsch,azensmichael)).
neg(f(apieradegliesposti,apakulaalanj)).
neg(f(abruceayoung,amarinovichanton)).
neg(f(akarinthaler,avergnejeanpierre)).
neg(f(acorradofortuna,aapprederisfranck)).
neg(f(ajamessikking,abonnetchristiani)).
neg(f(amanliosgalambro,aromeclaudemichel)).
neg(f(ahumecronyn,ametcalfestephen)).
neg(f(aantonradichev,azensmichael)).
neg(f(adavidsontag,asciveresmarianna)).
neg(f(acaitlinoheaney,averhoevenpauli)).
neg(f(afirminerichard,apakulaalanj)).
neg(f(ajohnheard,amillergeorgei)).
neg(f(adonatellafinocchiaro,asurchadzhievstefani)).
neg(f(astanleytucci,akappesstphane)).
neg(f(amarkgantt,agutjahrrainer)).
neg(f(astefanpejchev,ametcalfestephen)).
neg(f(amanliosgalambro,atraykovatanas)).
neg(f(amichalbajor,aengelhardtwilhelm)).
neg(f(abenjaminmouton,aengelhardtwilhelm)).
neg(f(aivangrigorov,aengelhardtwilhelm)).
neg(f(adanielvonbargen,aapprederisfranck)).
neg(f(agabrieleferzetti,acatonjonesmichael)).
neg(f(abarbaratabita,akinkelmartin)).
neg(f(atizianalodato,atraykovatanas)).
neg(f(ajuttawachowiak,amillergeorgei)).
neg(f(acatherinezetajones,abraunbettinai)).
neg(f(asalvatorelazzaro,akrgnther)).
neg(f(aauroraquattrocchi,aladogedominique)).
neg(f(abrigittefossey,agutjahrrainer)).
neg(f(avyarakovacheva,abonnetchristiani)).
neg(f(achelcieross,avergnejeanpierre)).
neg(f(adidierdijoux,apunchevborislav)).
neg(f(aclaudiamessner,amarinovichanton)).
neg(f(amarcocavicchioli,aengelhardtwilhelm)).
neg(f(aandreasschwaiger,averhoevenpauli)).
neg(f(acorradofortuna,aaltmanroberti)).
neg(f(adanielvonbargen,abonnetchristiani)).
neg(f(asalvatorelazzaro,azensmichael)).
neg(f(aleahayres,agustemmanuelii)).
neg(f(ajaimzwoolvett,astephanbernhard)).
neg(f(amarkgantt,aromeclaudemichel)).
neg(f(aantoniettacarbonetti,akronthalerthomas)).
neg(f(anevenakokanova,averhoevenpauli)).
neg(f(apierrearditi,abraunbettinai)).
neg(f(anicholaswoodeson,abattiatofranco)).
neg(f(astanleytucci,asoderberghsteven)).
neg(f(astefandanailov,astephanbernhard)).
neg(f(abillcable,aaltmanroberti)).
neg(f(asonyadjulgerova,asurchadzhievstefani)).
neg(f(akostatsonev,apakulaalanj)).
neg(f(alorigalinski,atraykovatanas)).
neg(f(aneilmaskell,apakulaalanj)).
neg(f(atheresascholze,akinkelmartin)).
neg(f(adonatellafinocchiaro,aengelhardtwilhelm)).
neg(f(aivantonev,aladogedominique)).
neg(f(amarcospicuglia,averhoevenpauli)).
neg(f(aradarassimov,asoderberghsteven)).
neg(f(apaolaciampi,aladogedominique)).
neg(f(avincenzocrivello,abonnetchristiani)).
neg(f(aloccorbery,akronthalerthomas)).
neg(f(amarcocavicchioli,aromeclaudemichel)).
neg(f(asamshepard,atraykovatanas)).
neg(f(alorigalinski,apakulaalanj)).
neg(f(atimrobbins,akronthalerthomas)).
neg(f(arichardegrant,abonnetchristiani)).
neg(f(adonatellafinocchiaro,averhoevenpauli)).
neg(f(aginachiarelli,amarinovichanton)).
neg(f(asalvatorelazzaro,aaltmanroberti)).
neg(f(amarisaburger,abattiatofranco)).
neg(f(adinamerrill,abonnetchristiani)).
neg(f(anicholaswoodeson,aaltmanroberti)).
neg(f(avolkerranisch,asciveresmarianna)).
neg(f(acorradofortuna,aengelhardtwilhelm)).
neg(f(aileanarigano,ametcalfestephen)).
neg(f(aalexandrawinisky,akappesstphane)).
neg(f(alarrysontag,akrgnther)).
neg(f(ascottcaan,astephanbernhard)).
neg(f(aheathcotewilliams,agustemmanuelii)).
neg(f(acesareapolito,asurchadzhievstefani)).
neg(f(asamshepard,astephanbernhard)).
neg(f(alyubomirbachvarov,akappesstphane)).
neg(f(adonatellafinocchiaro,agrimaldiaurelioi)).
neg(f(avincentlecoeur,agustemmanuelii)).
neg(f(amarkgantt,akappesstphane)).
neg(f(amichaeldouglas,aklischstefan)).
neg(f(adenisarndt,akrgnther)).
neg(f(adeanstockwell,akronthalerthomas)).
neg(f(abradpitt,agrimaldiaurelioi)).
neg(f(akonstanzebreitebner,atonetticlaudio)).
neg(f(asotirmaynolovski,akrgnther)).
neg(f(akunkabaeva,ametcalfestephen)).
neg(f(amanueladolcemascolo,averhoevenpauli)).
neg(f(aauroraquattrocchi,ametcalfestephen)).
neg(f(adinaconnolly,amarinovichanton)).
neg(f(asaromiano,amarinovichanton)).
neg(f(amarcocavicchioli,aklischstefan)).
neg(f(aheathcotewilliams,abraunbettinai)).
neg(f(ajohnlithgow,akinkelmartin)).
neg(f(astefanpejchev,atraykovatanas)).
neg(f(agabrieleferzetti,aklischstefan)).
neg(f(agerdlohmeyer,aladogedominique)).
neg(f(abrnicebejo,atonetticlaudio)).
neg(f(ajohnheard,amarinovichanton)).
neg(f(ascottcaan,azensmichael)).
neg(f(athomasstielner,aromeclaudemichel)).
neg(f(astancollymore,amillergeorgei)).
neg(f(astancollymore,astephanbernhard)).
neg(f(alorigalinski,aengelhardtwilhelm)).
neg(f(aianholm,amarinovichanton)).
neg(f(aangelahall,abattiatofranco)).
neg(f(aindiravarma,azensmichael)).
neg(f(akonstanzebreitebner,aapprederisfranck)).
neg(f(anelsonpeltz,averhoevenpauli)).
neg(f(amichalbajor,abraunbettinai)).
neg(f(asheilapaterson,avergnejeanpierre)).
neg(f(awhoopigoldberg,amillergeorgei)).
neg(f(agretascacchi,amillergeorgei)).
neg(f(alloydalan,amarinovichanton)).
neg(f(amarkusbker,amarinovichanton)).
neg(f(afrancomirabella,aengelhardtwilhelm)).
neg(f(anormanarmour,aapprederisfranck)).
neg(f(adanielvonbargen,aaltmanroberti)).
neg(f(anicholaswoodeson,apunchevborislav)).
neg(f(amanueladolcemascolo,asoderberghsteven)).
neg(f(atimberrington,astephanbernhard)).
neg(f(aminianden,asummereric)).
neg(f(acoralyzahonero,acatonjonesmichael)).
neg(f(afloramontgomery,aaltmanroberti)).
neg(f(anormanarmour,agrimaldiaurelioi)).
neg(f(aheathcotewilliams,asciveresmarianna)).
neg(f(anicholaswoodeson,amarinovichanton)).
neg(f(abillyconnolly,agutjahrrainer)).
neg(f(apetyasilyanova,aengelhardtwilhelm)).
neg(f(astefanodionisi,aromeclaudemichel)).
neg(f(aivantonev,aapprederisfranck)).
neg(f(aantoninobruschetta,abraunbettinai)).
neg(f(asotirmaynolovski,atraykovatanas)).
neg(f(ajustinmonjo,aromeclaudemichel)).
neg(f(aginachiarelli,aaltmanroberti)).
neg(f(avincentdonofrio,apakulaalanj)).
neg(f(apetardespotov,azensmichael)).
neg(f(amarcospicuglia,astephanbernhard)).
neg(f(alaurabetti,aklischstefan)).
neg(f(astefandanailov,asciveresmarianna)).
neg(f(amarcoleonardi,apakulaalanj)).
neg(f(agabrieleferzetti,amarinovichanton)).
neg(f(astoychomazgalov,astephanbernhard)).
neg(f(atimrobbins,aengelhardtwilhelm)).
neg(f(aindiravarma,atraykovatanas)).
neg(f(adonatellafinocchiaro,atraykovatanas)).
neg(f(asamshepard,asoderberghsteven)).
neg(f(asalvatorelazzaro,abonnetchristiani)).
neg(f(adinaconnolly,apunchevborislav)).
neg(f(accilecassel,amillergeorgei)).
neg(f(amarcospicuglia,agustemmanuelii)).
neg(f(astefandanailov,akappesstphane)).
neg(f(aangelinasarova,apakulaalanj)).
neg(f(aivandimov,astephanbernhard)).
neg(f(acarmelogalati,atonetticlaudio)).
neg(f(amiguelferrer,atraykovatanas)).
neg(f(araffaeladavi,aengelhardtwilhelm)).
neg(f(alyubomirbobchevski,aladogedominique)).
neg(f(ajanchappell,agutjahrrainer)).
neg(f(amarcoleonardi,akronthalerthomas)).
neg(f(astanleytucci,aromeclaudemichel)).
neg(f(atommikulla,abonnetchristiani)).
neg(f(amarksangster,atonetticlaudio)).
neg(f(arichardegrant,amarinovichanton)).
neg(f(alaurabetti,azensmichael)).
neg(f(ajuttawachowiak,abattiatofranco)).
neg(f(asonyadjulgerova,aapprederisfranck)).
neg(f(astanleytucci,asummereric)).
neg(f(ajurneesmollett,amarinovichanton)).
neg(f(aconnorwiddows,agustemmanuelii)).
neg(f(ajaimzwoolvett,averhoevenpauli)).
neg(f(amarcocavicchioli,amarinovichanton)).
neg(f(ahughkeaysbyrne,akronthalerthomas)).
neg(f(amarccaleb,agustemmanuelii)).
neg(f(aeddasabatini,aklischstefan)).
neg(f(aleonardlansink,apunchevborislav)).
neg(f(adinamerrill,asciveresmarianna)).
neg(f(agiancarloscuderi,apakulaalanj)).
neg(f(asotirmaynolovski,abattiatofranco)).
neg(f(aantoninobruschetta,aklischstefan)).
neg(f(apetardespotov,amillergeorgei)).
neg(f(anicolegrimaudo,agustemmanuelii)).
neg(f(ajohnheard,aaltmanroberti)).
neg(f(aluciacammalleri,abattiatofranco)).
neg(f(acaitlinoheaney,abonnetchristiani)).
neg(f(adinaconnolly,amillergeorgei)).
neg(f(amariashopova,ametcalfestephen)).
neg(f(atonygoldwyn,asurchadzhievstefani)).
neg(f(aalicjajachiewicz,acatonjonesmichael)).
neg(f(adanielvonbargen,asciveresmarianna)).
neg(f(adanielvonbargen,asurchadzhievstefani)).
neg(f(aradarassimov,astephanbernhard)).
neg(f(abillyconnolly,acatonjonesmichael)).
neg(f(aleahayres,amarinovichanton)).
neg(f(aluciacammalleri,avergnejeanpierre)).
neg(f(afabiolobello,abonnetchristiani)).
neg(f(aestefanacastro,akinkelmartin)).
neg(f(aauroraquattrocchi,amillergeorgei)).
neg(f(anicholaswoodeson,akinkelmartin)).
neg(f(acarmelogalati,akappesstphane)).
neg(f(adanielvonbargen,abraunbettinai)).
neg(f(adeanstockwell,averhoevenpauli)).
neg(f(ajohnlithgow,asurchadzhievstefani)).
neg(f(abarbaratabita,asurchadzhievstefani)).
neg(f(awayneknight,avergnejeanpierre)).
neg(f(arobyndouglass,apakulaalanj)).
neg(f(aalexandrawinisky,akrgnther)).
neg(f(abrigittefossey,atonetticlaudio)).
neg(f(adavidthewlis,agustemmanuelii)).
neg(f(ahumecronyn,akinkelmartin)).
neg(f(aestefanacastro,asummereric)).
neg(f(agabriellelazure,apakulaalanj)).
neg(f(agilbellows,apakulaalanj)).
neg(f(aguillaumeromain,aengelhardtwilhelm)).
neg(f(acarolflorence,amarinovichanton)).
neg(f(amichaeldouglas,agrimaldiaurelioi)).
neg(f(anevenakokanova,avergnejeanpierre)).
neg(f(ajaimzwoolvett,asummereric)).
neg(f(adontiffany,akrgnther)).
neg(f(ajanchappell,averhoevenpauli)).
neg(f(afrankpatton,acatonjonesmichael)).
neg(f(ahumecronyn,avergnejeanpierre)).
neg(f(aellenthomas,apakulaalanj)).
neg(f(ahubertmulzer,abonnetchristiani)).
neg(f(acorradofortuna,asummereric)).
neg(f(abarbaratabita,aengelhardtwilhelm)).
neg(f(ajohnheard,astephanbernhard)).
neg(f(ajuliaroberts,akinkelmartin)).
neg(f(adorothymalone,amillergeorgei)).
neg(f(aestefanacastro,asurchadzhievstefani)).
neg(f(aantoniettacarbonetti,aaltmanroberti)).
neg(f(anelsonpeltz,azensmichael)).
neg(f(aulrichmhe,apakulaalanj)).
neg(f(amarksangster,akrgnther)).
neg(f(ajohnlithgow,atonetticlaudio)).
neg(f(ajackmcgee,amillergeorgei)).
neg(f(ajackmcgee,acatonjonesmichael)).
neg(f(aheathcotewilliams,averhoevenpauli)).
neg(f(amaxmller,azensmichael)).
neg(f(anicolegrimaudo,atraykovatanas)).
neg(f(aleahayres,avergnejeanpierre)).
neg(f(asonyadjulgerova,agutjahrrainer)).
neg(f(ajannowicki,akronthalerthomas)).
neg(f(astevekuhn,akrgnther)).
neg(f(afrancishuster,asurchadzhievstefani)).
neg(f(aeddasabatini,akappesstphane)).
neg(f(alyubomirbobchevski,abattiatofranco)).
neg(f(astephentobolowsky,aladogedominique)).
neg(f(ajurneesmollett,aengelhardtwilhelm)).
neg(f(aganchoganchev,aaltmanroberti)).
neg(f(adavidthewlis,akronthalerthomas)).
neg(f(aleilanisarelle,akinkelmartin)).
neg(f(avincenzocrivello,agustemmanuelii)).
neg(f(amarcospicuglia,asummereric)).
neg(f(agabriellelazure,averhoevenpauli)).
neg(f(amikhailmikhajlov,akronthalerthomas)).
neg(f(aenzodimartino,aaltmanroberti)).
neg(f(ahubertmulzer,avergnejeanpierre)).
neg(f(afrancomirabella,asummereric)).
neg(f(athomasstielner,amarinovichanton)).
neg(f(afrancomirabella,akinkelmartin)).
neg(f(ageorgistamatov,abattiatofranco)).
neg(f(adinamerrill,apunchevborislav)).
neg(f(akirilyanev,astephanbernhard)).
neg(f(agusmercurio,aengelhardtwilhelm)).
neg(f(awayneknight,akappesstphane)).
neg(f(amiguelferrer,asoderberghsteven)).
neg(f(abruceayoung,asciveresmarianna)).
neg(f(astanleyanderson,amillergeorgei)).
neg(f(apetergallagher,agutjahrrainer)).
neg(f(abrigittefossey,asoderberghsteven)).
neg(f(aivankondov,abattiatofranco)).
neg(f(aanthonyheald,ametcalfestephen)).
neg(f(aellenthomas,abattiatofranco)).
neg(f(apetergallagher,akappesstphane)).
neg(f(aleilanisarelle,akronthalerthomas)).
neg(f(alewissmith,abonnetchristiani)).
neg(f(afranoisechristophe,acatonjonesmichael)).
neg(f(alaurabetti,astephanbernhard)).
neg(f(amarkgantt,amarinovichanton)).
neg(f(agusmercurio,abonnetchristiani)).
neg(f(aganchoganchev,asurchadzhievstefani)).
neg(f(amichaeldouglas,atraykovatanas)).
neg(f(amanueladolcemascolo,atraykovatanas)).
neg(f(anicolegrimaudo,aromeclaudemichel)).
neg(f(akunkabaeva,averhoevenpauli)).
neg(f(adietermann,aladogedominique)).
neg(f(afredward,amarinovichanton)).
neg(f(atheresascholze,aengelhardtwilhelm)).
neg(f(ajohnfinn,atonetticlaudio)).
neg(f(astevekuhn,acatonjonesmichael)).
neg(f(aterenceharvey,avergnejeanpierre)).
neg(f(avolkerranisch,akronthalerthomas)).
neg(f(atheresascholze,aklischstefan)).
neg(f(aindiravarma,asciveresmarianna)).
neg(f(asavahashamov,agustemmanuelii)).
neg(f(adorothymalone,aklischstefan)).
neg(f(aheathcotewilliams,avergnejeanpierre)).
neg(f(atommikulla,aapprederisfranck)).
neg(f(alarrysontag,aklischstefan)).
neg(f(aleilanisarelle,aaltmanroberti)).
neg(f(adillonmoen,asummereric)).
neg(f(aluciacammalleri,atraykovatanas)).
neg(f(adanielegalea,aromeclaudemichel)).
neg(f(aemilmarkov,agutjahrrainer)).
neg(f(astephentobolowsky,abonnetchristiani)).
neg(f(aannamariagherardi,avergnejeanpierre)).
neg(f(adanielegalea,azensmichael)).
neg(f(abradpitt,atonetticlaudio)).
neg(f(aneilmaskell,atraykovatanas)).
neg(f(aalicjajachiewicz,apakulaalanj)).
neg(f(aluciacammalleri,apakulaalanj)).
neg(f(aneilmaskell,abattiatofranco)).
neg(f(acharlotterampling,akinkelmartin)).
neg(f(avincentlecoeur,agutjahrrainer)).
neg(f(aenzodimartino,aengelhardtwilhelm)).
neg(f(acarolflorence,asciveresmarianna)).
neg(f(aginachiarelli,asciveresmarianna)).
neg(f(ajohnfinn,aengelhardtwilhelm)).
neg(f(apenlopecruz,abraunbettinai)).
neg(f(ahughkeaysbyrne,agustemmanuelii)).
neg(f(ajackmcgee,aapprederisfranck)).
neg(f(awhoopigoldberg,aengelhardtwilhelm)).
neg(f(abogomilsimeonov,atonetticlaudio)).
neg(f(aheathcotewilliams,atraykovatanas)).
neg(f(ajohnheard,aromeclaudemichel)).
neg(f(abrnicebejo,abattiatofranco)).
neg(f(afrankcturner,astephanbernhard)).
neg(f(atizianalodato,apunchevborislav)).
neg(f(apaolaciampi,aengelhardtwilhelm)).
neg(f(abradpitt,ametcalfestephen)).
neg(f(aindiravarma,asoderberghsteven)).
neg(f(aganchoganchev,azensmichael)).
neg(f(amanueladolcemascolo,akappesstphane)).
neg(f(ahubertmulzer,asummereric)).
neg(f(acorradofortuna,acatonjonesmichael)).
neg(f(avannifois,asoderberghsteven)).
neg(f(akunkabaeva,asummereric)).
neg(f(aviktordanchenko,agustemmanuelii)).
neg(f(aantonradichev,acatonjonesmichael)).
neg(f(amichaeldouglas,apakulaalanj)).
neg(f(abillyconnolly,apunchevborislav)).
neg(f(aserenaautieri,asoderberghsteven)).
neg(f(aandygarcia,apakulaalanj)).
neg(f(abruceayoung,amillergeorgei)).
neg(f(atzvetolyubrakovski,asoderberghsteven)).
neg(f(aeddiejemison,akinkelmartin)).
neg(f(afrancomirabella,ametcalfestephen)).
neg(f(anelsonpeltz,aapprederisfranck)).
neg(f(aeddasabatini,aaltmanroberti)).
neg(f(aestefanacastro,abonnetchristiani)).
neg(f(akarinthaler,akappesstphane)).
neg(f(ahubertmulzer,akappesstphane)).
neg(f(astanleyanderson,asurchadzhievstefani)).
neg(f(abarbaratabita,akappesstphane)).
neg(f(ajaimzwoolvett,aklischstefan)).
neg(f(abradpitt,agustemmanuelii)).
neg(f(ajamessikking,azensmichael)).
neg(f(amaurolenares,abattiatofranco)).
neg(f(anicolegrimaudo,aaltmanroberti)).
neg(f(alloydalan,apakulaalanj)).
neg(f(atzvetolyubrakovski,aaltmanroberti)).
neg(f(abogomilsimeonov,agrimaldiaurelioi)).
neg(f(astanleyanderson,atonetticlaudio)).
neg(f(afrancomirabella,aromeclaudemichel)).
neg(f(aantoninobruschetta,avergnejeanpierre)).
neg(f(adavidthewlis,averhoevenpauli)).
neg(f(aauroraquattrocchi,akinkelmartin)).
neg(f(apieradegliesposti,acatonjonesmichael)).
neg(f(apetergallagher,aromeclaudemichel)).
neg(f(ajeannetripplehorn,akronthalerthomas)).
neg(f(aceceliaannbirt,aengelhardtwilhelm)).
neg(f(abiagiobarone,apakulaalanj)).
neg(f(aconsuelolupo,akappesstphane)).
neg(f(amanueladolcemascolo,aromeclaudemichel)).
neg(f(amarccaleb,atraykovatanas)).
neg(f(asamshepard,akinkelmartin)).
neg(f(apieradegliesposti,asurchadzhievstefani)).
neg(f(agabrieleferzetti,ametcalfestephen)).
neg(f(amichalbajor,agustemmanuelii)).
neg(f(asharonstone,agustemmanuelii)).
neg(f(amichaeldouglas,asciveresmarianna)).
neg(f(aangelinasarova,avergnejeanpierre)).
neg(f(astefanpejchev,acatonjonesmichael)).
neg(f(abogomilsimeonov,asummereric)).
neg(f(adontiffany,apakulaalanj)).
neg(f(afredward,asummereric)).
neg(f(aheathcotewilliams,asoderberghsteven)).
neg(f(adebraengle,abattiatofranco)).
neg(f(asaromiano,avergnejeanpierre)).
neg(f(aalicjajachiewicz,akinkelmartin)).
neg(f(amarkgantt,agustemmanuelii)).
neg(f(adenzelwashington,ametcalfestephen)).
neg(f(atzenokandov,averhoevenpauli)).
neg(f(astephentobolowsky,aklischstefan)).
neg(f(acesareapolito,abraunbettinai)).
neg(f(aianholm,apunchevborislav)).
neg(f(acaseyaffleck,aapprederisfranck)).
neg(f(aheathcotewilliams,akronthalerthomas)).
neg(f(anicholaswoodeson,akrgnther)).
neg(f(agilbellows,atonetticlaudio)).
neg(f(aheathcotewilliams,abonnetchristiani)).
neg(f(atimberrington,amillergeorgei)).
neg(f(akonstanzebreitebner,averhoevenpauli)).
neg(f(aivankondov,abonnetchristiani)).
neg(f(anevenakokanova,asoderberghsteven)).
neg(f(aantoninobruschetta,agrimaldiaurelioi)).
neg(f(aviktordanchenko,aromeclaudemichel)).
neg(f(asheilapaterson,amillergeorgei)).
neg(f(ahristodinev,acatonjonesmichael)).
neg(f(ahughkeaysbyrne,agrimaldiaurelioi)).
neg(f(arobertculp,asurchadzhievstefani)).
neg(f(achelcieross,amarinovichanton)).
neg(f(adanielegalea,aaltmanroberti)).
neg(f(adietermann,akappesstphane)).
neg(f(anicolegrimaudo,amarinovichanton)).
neg(f(abradpitt,aromeclaudemichel)).
neg(f(asaromiano,akronthalerthomas)).
neg(f(aestefanacastro,aromeclaudemichel)).
neg(f(abrionjames,amillergeorgei)).
neg(f(alorigalinski,akinkelmartin)).
neg(f(ajohnheard,aklischstefan)).
neg(f(avincenzocrivello,amillergeorgei)).
neg(f(aleahayres,akinkelmartin)).
neg(f(ajuliedray,atonetticlaudio)).
neg(f(asavahashamov,atonetticlaudio)).
neg(f(afrancomirabella,amillergeorgei)).
neg(f(amarisaburger,amillergeorgei)).
neg(f(aivantonev,akappesstphane)).
neg(f(aenzodimartino,abattiatofranco)).
neg(f(atizianalodato,akappesstphane)).
neg(f(agiancarloscuderi,asurchadzhievstefani)).
neg(f(asheilapaterson,agrimaldiaurelioi)).
neg(f(asavahashamov,averhoevenpauli)).
neg(f(acynthiastevenson,agutjahrrainer)).
neg(f(anormanarmour,azensmichael)).
neg(f(adontiffany,asciveresmarianna)).
neg(f(ajrggudzuhn,aapprederisfranck)).
neg(f(avincenzocrivello,akronthalerthomas)).
neg(f(agiancarloscuderi,acatonjonesmichael)).
neg(f(amarcospicuglia,avergnejeanpierre)).
neg(f(aluciacammalleri,apunchevborislav)).
neg(f(aconnorwiddows,agutjahrrainer)).
neg(f(apaullnolan,avergnejeanpierre)).
neg(f(anelsonpeltz,apakulaalanj)).
neg(f(ajrggudzuhn,asoderberghsteven)).
neg(f(akostatsonev,astephanbernhard)).
neg(f(adannflorek,apunchevborislav)).
neg(f(adimitarhadzhiyanev,amarinovichanton)).
neg(f(asharonstone,akinkelmartin)).
neg(f(afrancishuster,agutjahrrainer)).
neg(f(abrnicebejo,akronthalerthomas)).
neg(f(ajohnlithgow,agutjahrrainer)).
neg(f(avincentdonofrio,asurchadzhievstefani)).
neg(f(asamshepard,aapprederisfranck)).
neg(f(aemiliaradeva,agrimaldiaurelioi)).
neg(f(alylelovett,amillergeorgei)).
neg(f(astoychomazgalov,amillergeorgei)).
neg(f(adeanstockwell,avergnejeanpierre)).
neg(f(ajorgerhernandez,aapprederisfranck)).
neg(f(arichardegrant,aromeclaudemichel)).
neg(f(afrankpatton,abattiatofranco)).
neg(f(aeddiejemison,averhoevenpauli)).
neg(f(adidierdijoux,amillergeorgei)).
neg(f(agiancarloscuderi,aaltmanroberti)).
neg(f(acoralyzahonero,avergnejeanpierre)).
neg(f(amarcospicuglia,aklischstefan)).
neg(f(astephentobolowsky,amillergeorgei)).
neg(f(asalvatorelazzaro,amillergeorgei)).
neg(f(anicolegrimaudo,akappesstphane)).
neg(f(ajurneesmollett,abonnetchristiani)).
neg(f(apetergallagher,asurchadzhievstefani)).
neg(f(akirilyanev,asciveresmarianna)).
neg(f(aestefanacastro,agustemmanuelii)).
neg(f(adanielvonbargen,amillergeorgei)).
neg(f(aanthonyheald,atraykovatanas)).
neg(f(ajeannetripplehorn,astephanbernhard)).
neg(f(ajrggudzuhn,aklischstefan)).
neg(f(amichaeldouglas,akinkelmartin)).
neg(f(aradarassimov,acatonjonesmichael)).
neg(f(amanliosgalambro,asummereric)).
neg(f(aantoniettacarbonetti,abonnetchristiani)).
neg(f(afrancomirabella,aapprederisfranck)).
neg(f(aangelinasarova,asciveresmarianna)).
neg(f(adanielvonbargen,asummereric)).
neg(f(adavidsontag,atonetticlaudio)).
neg(f(arobyndouglass,avergnejeanpierre)).
neg(f(aangelahall,aapprederisfranck)).
neg(f(adenzelwashington,amarinovichanton)).
neg(f(aconsuelolupo,abraunbettinai)).
neg(f(astanleyanderson,atraykovatanas)).
neg(f(ajuliaroberts,akrgnther)).
neg(f(adinamerrill,abraunbettinai)).
neg(f(aberniemac,aromeclaudemichel)).
neg(f(adorothymalone,agustemmanuelii)).
neg(f(arenateschroeter,atraykovatanas)).
neg(f(amarenschumacher,azensmichael)).
neg(f(afrankcturner,asummereric)).
neg(f(ajuttawachowiak,apakulaalanj)).
neg(f(agabrieleferzetti,akinkelmartin)).
neg(f(apaolaciampi,akrgnther)).
neg(f(apaolaciampi,akinkelmartin)).
neg(f(acharlotterampling,asurchadzhievstefani)).
neg(f(amarcospicuglia,asciveresmarianna)).
neg(f(adebraengle,agustemmanuelii)).
neg(f(agerdlohmeyer,agustemmanuelii)).
neg(f(amaurizionicolosi,abraunbettinai)).
neg(f(aivankondov,agutjahrrainer)).
neg(f(apaolaciampi,amarinovichanton)).
neg(f(aandreasschwaiger,abattiatofranco)).
neg(f(adenisarndt,akinkelmartin)).
neg(f(apatricejuiff,abraunbettinai)).
neg(f(ajuliaroberts,acatonjonesmichael)).
neg(f(aangelinasarova,ametcalfestephen)).
neg(f(adontiffany,agustemmanuelii)).
neg(f(adavidthewlis,astephanbernhard)).
neg(f(agabrieleferzetti,aladogedominique)).
neg(f(ageorgedzundza,abonnetchristiani)).
neg(f(atimrobbins,amillergeorgei)).
neg(f(adinaconnolly,astephanbernhard)).
neg(f(afranoisechristophe,aklischstefan)).
neg(f(arichardegrant,asciveresmarianna)).
neg(f(arobyndouglass,aromeclaudemichel)).
neg(f(alorigalinski,averhoevenpauli)).
neg(f(ajaimzwoolvett,avergnejeanpierre)).
neg(f(aluciacammalleri,aladogedominique)).
neg(f(adeanstockwell,abonnetchristiani)).
neg(f(atheresascholze,apakulaalanj)).
neg(f(aelliottgould,agutjahrrainer)).
neg(f(aandygarcia,aengelhardtwilhelm)).
neg(f(astefanodionisi,atraykovatanas)).
neg(f(aguillaumeromain,asummereric)).
neg(f(aradarassimov,asurchadzhievstefani)).
neg(f(alaurabetti,atonetticlaudio)).
neg(f(acoralyzahonero,asurchadzhievstefani)).
neg(f(aileanarigano,atraykovatanas)).
neg(f(amarenschumacher,aromeclaudemichel)).
neg(f(aantoninobruschetta,akappesstphane)).
neg(f(atimothypaulperez,aapprederisfranck)).
neg(f(aelliottgould,akappesstphane)).
neg(f(alyubomirkanev,atonetticlaudio)).
neg(f(atzvetolyubrakovski,ametcalfestephen)).
neg(f(apaolaciampi,asurchadzhievstefani)).
neg(f(astevekuhn,akappesstphane)).
neg(f(arobyndouglass,aladogedominique)).
neg(f(abruceayoung,aromeclaudemichel)).
neg(f(agesinecukrowski,akappesstphane)).
neg(f(apaullnolan,agutjahrrainer)).
neg(f(anelsonpeltz,atraykovatanas)).
neg(f(asharonstone,abattiatofranco)).
neg(f(apaolaciampi,abraunbettinai)).
neg(f(aellenthomas,abonnetchristiani)).
neg(f(aberniemac,asciveresmarianna)).
neg(f(alloydalan,aromeclaudemichel)).
neg(f(asamantharnier,abonnetchristiani)).
neg(f(astanleyanderson,abattiatofranco)).
neg(f(athomasstielner,amillergeorgei)).
neg(f(adenzelwashington,asurchadzhievstefani)).
neg(f(amarcoleonardi,aromeclaudemichel)).
neg(f(alucavitrano,acatonjonesmichael)).
neg(f(agiancarloscuderi,asciveresmarianna)).
neg(f(agretascacchi,asoderberghsteven)).
neg(f(asamshepard,averhoevenpauli)).
neg(f(astevekalfa,astephanbernhard)).
neg(f(aedkross,asummereric)).
neg(f(awilliamatherton,acatonjonesmichael)).
neg(f(arenateschroeter,asurchadzhievstefani)).
neg(f(asharonstone,akronthalerthomas)).
neg(f(afrancishuster,aaltmanroberti)).
neg(f(avolkerranisch,aladogedominique)).
neg(f(alyubomirbobchevski,akappesstphane)).
neg(f(avincentdonofrio,apunchevborislav)).
neg(f(abarbaratabita,azensmichael)).
neg(f(astefanpejchev,aapprederisfranck)).
neg(f(adorothymalone,ametcalfestephen)).
neg(f(akonstanzebreitebner,aklischstefan)).
neg(f(apaullnolan,amarinovichanton)).
neg(f(awhoopigoldberg,akappesstphane)).
neg(f(aivangrigorov,agutjahrrainer)).
neg(f(aelliottgould,asurchadzhievstefani)).
neg(f(aginachiarelli,agutjahrrainer)).
neg(f(aulrichmhe,akappesstphane)).
neg(f(aivantonev,averhoevenpauli)).
neg(f(ajrggudzuhn,apunchevborislav)).
neg(f(alyubomirbobchevski,asoderberghsteven)).
neg(f(aneilmaskell,agutjahrrainer)).
neg(f(apatricejuiff,ametcalfestephen)).
neg(f(asonyadjulgerova,asummereric)).
neg(f(acatherinezetajones,aklischstefan)).
neg(f(aantoniettacarbonetti,aromeclaudemichel)).
neg(f(avincenzocrivello,agutjahrrainer)).
neg(f(ajamessikking,akronthalerthomas)).
neg(f(apaullnolan,agrimaldiaurelioi)).
neg(f(adavidthewlis,aapprederisfranck)).
neg(f(asavahashamov,akinkelmartin)).
neg(f(adavidmorrissey,abraunbettinai)).
neg(f(aleahayres,asurchadzhievstefani)).
neg(f(adietermann,akrgnther)).
neg(f(adonatellafinocchiaro,aklischstefan)).
neg(f(astanleyanderson,acatonjonesmichael)).
neg(f(aianholm,averhoevenpauli)).
neg(f(adavidthewlis,abraunbettinai)).
neg(f(avolkerranisch,aapprederisfranck)).
neg(f(apetergallagher,abattiatofranco)).
neg(f(aminianden,acatonjonesmichael)).
neg(f(ajustinmonjo,asummereric)).
neg(f(ajuliaroberts,aromeclaudemichel)).
neg(f(ajuliaroberts,abraunbettinai)).
neg(f(agretascacchi,apakulaalanj)).
neg(f(apetardespotov,aladogedominique)).
neg(f(amariashopova,agrimaldiaurelioi)).
neg(f(aannejacques,avergnejeanpierre)).
neg(f(adimitarhadzhiyanev,asoderberghsteven)).
neg(f(astoychomazgalov,averhoevenpauli)).
neg(f(aradarassimov,azensmichael)).
neg(f(apenlopecruz,aaltmanroberti)).
neg(f(asydneypollack,asurchadzhievstefani)).
neg(f(adavidarnett,abonnetchristiani)).
neg(f(aterenceharvey,atraykovatanas)).
neg(f(asotirmaynolovski,astephanbernhard)).
neg(f(aantoniettacarbonetti,ametcalfestephen)).
neg(f(ageorgistamatov,asoderberghsteven)).
neg(f(acarolflorence,akronthalerthomas)).
neg(f(apierrearditi,aromeclaudemichel)).
neg(f(aviktordanchenko,aaltmanroberti)).
neg(f(ajuliedray,agustemmanuelii)).
neg(f(aemilmarkov,aladogedominique)).
neg(f(alewissmith,avergnejeanpierre)).
neg(f(adietermann,amillergeorgei)).
neg(f(adavidmorrissey,astephanbernhard)).
neg(f(agabrieleferzetti,akronthalerthomas)).
neg(f(aemilmarkov,acatonjonesmichael)).
neg(f(ajurneesmollett,aladogedominique)).
neg(f(apieradegliesposti,avergnejeanpierre)).
neg(f(asalvatorelazzaro,apakulaalanj)).
neg(f(aguillaumeromain,abraunbettinai)).
neg(f(agerdlohmeyer,apunchevborislav)).
neg(f(acatherinezetajones,asummereric)).
neg(f(apetergallagher,asoderberghsteven)).
neg(f(acatherinezetajones,averhoevenpauli)).
neg(f(amanliosgalambro,aaltmanroberti)).
neg(f(akarinthaler,acatonjonesmichael)).
neg(f(atizianalodato,atonetticlaudio)).
neg(f(abarbaratabita,aaltmanroberti)).
neg(f(alylelovett,aapprederisfranck)).
neg(f(astancollymore,akronthalerthomas)).
neg(f(abarbaratabita,avergnejeanpierre)).
neg(f(akunkabaeva,akappesstphane)).
neg(f(avincentdonofrio,asciveresmarianna)).
neg(f(adonatellafinocchiaro,agustemmanuelii)).
neg(f(aganchoganchev,aklischstefan)).
neg(f(afranoisechristophe,asoderberghsteven)).
neg(f(adenisarndt,amarinovichanton)).
neg(f(aconnorwiddows,abattiatofranco)).
neg(f(araffaeladavi,acatonjonesmichael)).
neg(f(abarbaratabita,aromeclaudemichel)).
neg(f(amiguelferrer,aaltmanroberti)).
neg(f(avincenzocrivello,apunchevborislav)).
neg(f(aluciacammalleri,akinkelmartin)).
neg(f(amarksangster,aladogedominique)).
neg(f(afirminerichard,akrgnther)).
neg(f(aivankondov,azensmichael)).
neg(f(atzvetolyubrakovski,aladogedominique)).
neg(f(afredward,aklischstefan)).
neg(f(alloydalan,aengelhardtwilhelm)).
neg(f(amarksangster,avergnejeanpierre)).
neg(f(ascottcaan,akrgnther)).
neg(f(ajuttawachowiak,aapprederisfranck)).
neg(f(aandreasschwaiger,asummereric)).
neg(f(avolkerranisch,ametcalfestephen)).
neg(f(agilbellows,averhoevenpauli)).
neg(f(amaxmller,asciveresmarianna)).
neg(f(adavidthewlis,abonnetchristiani)).
neg(f(achelcieross,apakulaalanj)).
neg(f(ahristodinev,aromeclaudemichel)).
neg(f(aenzodimartino,azensmichael)).
neg(f(adietermann,akinkelmartin)).
neg(f(aalexandrawinisky,akronthalerthomas)).
neg(f(acesareapolito,asoderberghsteven)).
neg(f(asharonstone,asciveresmarianna)).
neg(f(adillonmoen,akronthalerthomas)).
neg(f(amichalbajor,amillergeorgei)).
neg(f(aclaudiamessner,asoderberghsteven)).
neg(f(afrancomirabella,abonnetchristiani)).
neg(f(apetyasilyanova,apunchevborislav)).
neg(f(amarkgantt,abattiatofranco)).
neg(f(abiagiobarone,abattiatofranco)).
neg(f(ajackmcgee,agrimaldiaurelioi)).
neg(f(abrnicebejo,aladogedominique)).
neg(f(agilbellows,amillergeorgei)).
neg(f(apetyasilyanova,aromeclaudemichel)).
neg(f(afrancishuster,amillergeorgei)).
neg(f(aangelinasarova,aladogedominique)).
neg(f(aemiliaradeva,asummereric)).
neg(f(atzvetolyubrakovski,akinkelmartin)).
neg(f(aconnorwiddows,averhoevenpauli)).
neg(f(akarinthaler,amarinovichanton)).
neg(f(araffaeladavi,aromeclaudemichel)).
neg(f(astanleyanderson,astephanbernhard)).
neg(f(akostatsonev,akronthalerthomas)).
neg(f(alorigalinski,asurchadzhievstefani)).
neg(f(aclaudiamessner,akrgnther)).
neg(f(acatherinezetajones,astephanbernhard)).
neg(f(aellenthomas,azensmichael)).
neg(f(afabiolobello,akappesstphane)).
neg(f(ajohnheard,aladogedominique)).
neg(f(abrionjames,akrgnther)).
neg(f(atzvetolyubrakovski,amillergeorgei)).
neg(f(avincenzocrivello,aklischstefan)).
neg(f(amarcospicuglia,amarinovichanton)).
neg(f(agiancarloscuderi,agustemmanuelii)).
neg(f(aauroraquattrocchi,akrgnther)).
neg(f(abenjohnson,averhoevenpauli)).
neg(f(astefanpejchev,asurchadzhievstefani)).
neg(f(ajorgerhernandez,akrgnther)).
neg(f(ageorgistamatov,azensmichael)).
neg(f(alucavitrano,averhoevenpauli)).
neg(f(aedkross,aengelhardtwilhelm)).
neg(f(astanleyanderson,aladogedominique)).
neg(f(aluciacammalleri,akappesstphane)).
neg(f(ahristodinev,apunchevborislav)).
neg(f(akonstanzebreitebner,abonnetchristiani)).
neg(f(alyubomirbobchevski,amarinovichanton)).
neg(f(astevekuhn,aromeclaudemichel)).
neg(f(ajurneesmollett,abraunbettinai)).
neg(f(aemilmarkov,aromeclaudemichel)).
neg(f(ageorgeclooney,apakulaalanj)).
neg(f(adenzelwashington,atonetticlaudio)).
neg(f(abrigittefossey,amarinovichanton)).
neg(f(adeanstockwell,agustemmanuelii)).
neg(f(aconnorwiddows,aapprederisfranck)).
neg(f(aradarassimov,asciveresmarianna)).
neg(f(anelsonpeltz,asciveresmarianna)).
neg(f(alyubomirbobchevski,amillergeorgei)).
neg(f(amarenschumacher,aladogedominique)).
neg(f(anikoladadov,asurchadzhievstefani)).
neg(f(astefanpetrov,avergnejeanpierre)).
neg(f(atonygoldwyn,acatonjonesmichael)).
neg(f(ajackmcgee,apakulaalanj)).
neg(f(apaullnolan,astephanbernhard)).
neg(f(anicholaswoodeson,asummereric)).
neg(f(astefandanailov,aladogedominique)).
neg(f(amarcocavicchioli,atraykovatanas)).
neg(f(atizianalodato,asummereric)).
neg(f(awilliamatherton,abraunbettinai)).
neg(f(abillyconnolly,asciveresmarianna)).
neg(f(aenzodimartino,astephanbernhard)).
neg(f(abruceayoung,astephanbernhard)).
neg(f(amaurolenares,aapprederisfranck)).
neg(f(aalancpeterson,aapprederisfranck)).
neg(f(aestefanacastro,ametcalfestephen)).
neg(f(amanliosgalambro,atonetticlaudio)).
neg(f(agusmercurio,atraykovatanas)).
neg(f(adietermann,acatonjonesmichael)).
neg(f(aivanbratanov,aapprederisfranck)).
neg(f(anikoladadov,azensmichael)).
neg(f(amaurizionicolosi,agustemmanuelii)).
neg(f(adenisarndt,agutjahrrainer)).
neg(f(adavidarnett,agustemmanuelii)).
neg(f(astevekuhn,aklischstefan)).
neg(f(asheilapaterson,asoderberghsteven)).
neg(f(accilecassel,acatonjonesmichael)).
neg(f(aelliottgould,abonnetchristiani)).
neg(f(anicolegrimaudo,aengelhardtwilhelm)).
neg(f(abrigittefossey,astephanbernhard)).
neg(f(avolkerranisch,atonetticlaudio)).
neg(f(apieradegliesposti,amillergeorgei)).
neg(f(aalancpeterson,agustemmanuelii)).
neg(f(adanielegalea,akronthalerthomas)).
neg(f(amarksangster,abonnetchristiani)).
neg(f(astefandanailov,abattiatofranco)).
neg(f(avyarakovacheva,asciveresmarianna)).
neg(f(aellenthomas,asciveresmarianna)).
neg(f(aandygarcia,acatonjonesmichael)).
neg(f(ajustinmonjo,ametcalfestephen)).
neg(f(astephentobolowsky,akrgnther)).
neg(f(ajeannetripplehorn,aklischstefan)).
neg(f(aludwigbriand,agrimaldiaurelioi)).
neg(f(amichalbajor,akappesstphane)).
neg(f(anicholaswoodeson,avergnejeanpierre)).
neg(f(ajrggudzuhn,avergnejeanpierre)).
neg(f(astancollymore,agustemmanuelii)).
neg(f(astefanodionisi,acatonjonesmichael)).
neg(f(amarccaleb,akrgnther)).
neg(f(atimothypaulperez,aengelhardtwilhelm)).
neg(f(akostatsonev,agutjahrrainer)).
neg(f(asalvatorelazzaro,averhoevenpauli)).
neg(f(amiguelferrer,akronthalerthomas)).
neg(f(astevekuhn,azensmichael)).
neg(f(aeddiejemison,abattiatofranco)).
neg(f(astevekuhn,abonnetchristiani)).
neg(f(aantonradichev,aengelhardtwilhelm)).
neg(f(aguillaumeromain,agrimaldiaurelioi)).
neg(f(acorradofortuna,aklischstefan)).
neg(f(arobertculp,atraykovatanas)).
neg(f(aleahayres,agutjahrrainer)).
neg(f(abradpitt,abonnetchristiani)).
neg(f(aminianden,aengelhardtwilhelm)).
neg(f(agretascacchi,atraykovatanas)).
neg(f(aantoniettacarbonetti,asummereric)).
neg(f(aginachiarelli,aapprederisfranck)).
neg(f(aleonardlansink,agutjahrrainer)).
neg(f(abillcable,agutjahrrainer)).
neg(f(aivandimov,apakulaalanj)).
neg(f(adillonmoen,akrgnther)).
neg(f(adavidmorrissey,aengelhardtwilhelm)).
neg(f(amariashopova,apakulaalanj)).
neg(f(amarkusbker,astephanbernhard)).
neg(f(acaseyaffleck,aladogedominique)).
neg(f(adavidmorrissey,apunchevborislav)).
neg(f(abarbaratabita,amarinovichanton)).
neg(f(alloydalan,abraunbettinai)).
neg(f(adietermann,atonetticlaudio)).
neg(f(adinaconnolly,abraunbettinai)).
neg(f(asavahashamov,astephanbernhard)).
neg(f(adebraengle,asurchadzhievstefani)).
neg(f(ajuttawachowiak,acatonjonesmichael)).
neg(f(anelsonpeltz,apunchevborislav)).
neg(f(astanleyanderson,abraunbettinai)).
neg(f(abenjaminmouton,aklischstefan)).
neg(f(afabiolobello,agustemmanuelii)).
neg(f(amarkgantt,averhoevenpauli)).
neg(f(aanthonyheald,agrimaldiaurelioi)).
neg(f(atzvetolyubrakovski,akrgnther)).
neg(f(afabiolobello,aaltmanroberti)).
neg(f(ahorstkummeth,astephanbernhard)).
neg(f(adimitarhadzhiyanev,asurchadzhievstefani)).
neg(f(aannejacques,averhoevenpauli)).
neg(f(aannejacques,apakulaalanj)).
neg(f(anikoladadov,abonnetchristiani)).
neg(f(avincenzocrivello,aapprederisfranck)).
neg(f(acarmelogalati,akinkelmartin)).
neg(f(alucavitrano,akinkelmartin)).
neg(f(astefanodionisi,ametcalfestephen)).
neg(f(adinamerrill,astephanbernhard)).
neg(f(avyarakovacheva,akronthalerthomas)).
neg(f(aannejacques,astephanbernhard)).
neg(f(achelcieross,agutjahrrainer)).
neg(f(aberniemac,atonetticlaudio)).
neg(f(agiancarloscuderi,atonetticlaudio)).
neg(f(aindiravarma,asummereric)).
neg(f(adinaconnolly,agrimaldiaurelioi)).
neg(f(adontiffany,abonnetchristiani)).
neg(f(abrionjames,averhoevenpauli)).
neg(f(acatherinezetajones,atonetticlaudio)).
neg(f(apenlopecruz,apakulaalanj)).
neg(f(astephentobolowsky,asoderberghsteven)).
neg(f(astevekuhn,averhoevenpauli)).
neg(f(asavahashamov,abattiatofranco)).
neg(f(aleahayres,abraunbettinai)).
neg(f(aconsuelolupo,aapprederisfranck)).
neg(f(abiagiobarone,aapprederisfranck)).
neg(f(avincentlecoeur,apakulaalanj)).
neg(f(aannamariagherardi,akronthalerthomas)).
neg(f(acaseyaffleck,apakulaalanj)).
neg(f(aalancpeterson,agutjahrrainer)).
neg(f(afrancishuster,azensmichael)).
neg(f(aconsuelolupo,abattiatofranco)).
neg(f(abruceayoung,azensmichael)).
neg(f(adebraengle,aromeclaudemichel)).
neg(f(alloydalan,akinkelmartin)).
neg(f(avincenzocrivello,apakulaalanj)).
neg(f(akostatsonev,asummereric)).
neg(f(acarolflorence,aladogedominique)).
neg(f(abrnicebejo,ametcalfestephen)).
neg(f(afabiolobello,atonetticlaudio)).
neg(f(amariashopova,avergnejeanpierre)).
neg(f(apaullnolan,abonnetchristiani)).
neg(f(aemilmarkov,akrgnther)).
neg(f(amarksangster,amarinovichanton)).
neg(f(ageorgedzundza,asciveresmarianna)).
neg(f(astefandanailov,aapprederisfranck)).
neg(f(amanueladolcemascolo,atonetticlaudio)).
neg(f(aarmelledeutsch,amarinovichanton)).
neg(f(ajeannetripplehorn,agustemmanuelii)).
neg(f(anicolegrimaudo,averhoevenpauli)).
neg(f(agusmercurio,asurchadzhievstefani)).
neg(f(aleahayres,akappesstphane)).
neg(f(acarmelogalati,amillergeorgei)).
neg(f(apieradegliesposti,abraunbettinai)).
neg(f(acarolflorence,abonnetchristiani)).
neg(f(aulrichmhe,aromeclaudemichel)).
neg(f(adietermann,aapprederisfranck)).
neg(f(aantonradichev,amillergeorgei)).
neg(f(akunkabaeva,apakulaalanj)).
neg(f(aloccorbery,atonetticlaudio)).
neg(f(aantonradichev,ametcalfestephen)).
neg(f(aminianden,aklischstefan)).
neg(f(ageorgedzundza,ametcalfestephen)).
neg(f(afrankcturner,apunchevborislav)).
neg(f(anormanarmour,akinkelmartin)).
neg(f(amarksangster,akronthalerthomas)).
neg(f(agesinecukrowski,averhoevenpauli)).
neg(f(aindiravarma,aengelhardtwilhelm)).
neg(f(aantonradichev,agutjahrrainer)).
neg(f(asalvatorelazzaro,atonetticlaudio)).
neg(f(avolkerranisch,acatonjonesmichael)).
neg(f(aleilanisarelle,abonnetchristiani)).
neg(f(adavidmorrissey,akrgnther)).
neg(f(ajamessikking,ametcalfestephen)).
neg(f(aalancpeterson,asciveresmarianna)).
neg(f(aeddiejemison,aengelhardtwilhelm)).
neg(f(ajeannetripplehorn,aladogedominique)).
neg(f(adimitarhadzhiyanev,asciveresmarianna)).
neg(f(aelliottgould,amarinovichanton)).
neg(f(athomasstielner,asurchadzhievstefani)).
neg(f(akonstanzebreitebner,akinkelmartin)).
neg(f(asamshepard,avergnejeanpierre)).
neg(f(ajuliedray,aklischstefan)).
neg(f(adorothymalone,akinkelmartin)).
neg(f(afredward,astephanbernhard)).
neg(f(akunkabaeva,aklischstefan)).
neg(f(astanleytucci,aladogedominique)).
neg(f(adenzelwashington,asciveresmarianna)).
neg(f(adillonmoen,abraunbettinai)).
neg(f(alaurabetti,apakulaalanj)).
neg(f(asydneypollack,avergnejeanpierre)).
neg(f(adinaconnolly,agutjahrrainer)).
neg(f(afrankpatton,atonetticlaudio)).
neg(f(aceceliaannbirt,aaltmanroberti)).
neg(f(aangelinasarova,akappesstphane)).
neg(f(aivandimov,azensmichael)).
neg(f(alloydalan,agutjahrrainer)).
neg(f(ajrggudzuhn,apakulaalanj)).
neg(f(ageorgistamatov,agustemmanuelii)).
neg(f(amarenschumacher,atraykovatanas)).
neg(f(agerdlohmeyer,agrimaldiaurelioi)).
neg(f(asheilapaterson,aengelhardtwilhelm)).
neg(f(adillonmoen,agutjahrrainer)).
neg(f(amarcoleonardi,ametcalfestephen)).
neg(f(aemilmarkov,aengelhardtwilhelm)).
neg(f(ageorgedzundza,amillergeorgei)).
neg(f(amarcocavicchioli,aapprederisfranck)).
neg(f(ajrggudzuhn,agustemmanuelii)).
neg(f(afrankcturner,akronthalerthomas)).
neg(f(aulrichmhe,amarinovichanton)).
neg(f(ahughkeaysbyrne,aladogedominique)).
neg(f(ahorstkummeth,agustemmanuelii)).
neg(f(adavidthewlis,agutjahrrainer)).
neg(f(aeddiejemison,aklischstefan)).
neg(f(aserenaautieri,akrgnther)).
neg(f(ahumecronyn,aapprederisfranck)).
neg(f(ajamessikking,akrgnther)).
neg(f(ahubertmulzer,averhoevenpauli)).
neg(f(alucavitrano,apunchevborislav)).
neg(f(atizianalodato,asoderberghsteven)).
neg(f(atzenokandov,akinkelmartin)).
neg(f(ajorgerhernandez,aengelhardtwilhelm)).
neg(f(adorothymalone,akronthalerthomas)).
neg(f(ahumecronyn,abraunbettinai)).
neg(f(ahughkeaysbyrne,astephanbernhard)).
neg(f(alyubomirbachvarov,akinkelmartin)).
neg(f(atizianalodato,asurchadzhievstefani)).
neg(f(astefanpetrov,apunchevborislav)).
neg(f(acaseyaffleck,aromeclaudemichel)).
neg(f(asotirmaynolovski,akronthalerthomas)).
neg(f(ajanchappell,abraunbettinai)).
neg(f(ageorgedzundza,asummereric)).
neg(f(adebraengle,asummereric)).
neg(f(akirilyanev,abattiatofranco)).
neg(f(aconsuelolupo,aengelhardtwilhelm)).
neg(f(agesinecukrowski,aapprederisfranck)).
neg(f(astoychomazgalov,akinkelmartin)).
neg(f(acaseyaffleck,apunchevborislav)).
neg(f(aterenceharvey,apakulaalanj)).
neg(f(afloramontgomery,amillergeorgei)).
neg(f(amarenschumacher,asummereric)).
neg(f(amaxmller,ametcalfestephen)).
neg(f(aanthonyheald,akinkelmartin)).
neg(f(asavahashamov,aklischstefan)).
neg(f(ajorgerhernandez,akappesstphane)).
neg(f(aluciacammalleri,agrimaldiaurelioi)).
neg(f(atonygoldwyn,averhoevenpauli)).
neg(f(aivanbratanov,aladogedominique)).
neg(f(asonyadjulgerova,akinkelmartin)).
neg(f(adonatellafinocchiaro,apakulaalanj)).
neg(f(atimrobbins,avergnejeanpierre)).
neg(f(akirilyanev,atonetticlaudio)).
neg(f(ascottcaan,aapprederisfranck)).
neg(f(afloramontgomery,agustemmanuelii)).
neg(f(apenlopecruz,asoderberghsteven)).
neg(f(abrionjames,aklischstefan)).
neg(f(aceceliaannbirt,akronthalerthomas)).
neg(f(aantoniettacarbonetti,apakulaalanj)).
neg(f(apetardespotov,apakulaalanj)).
neg(f(acarolflorence,apakulaalanj)).
neg(f(acharlotterampling,aaltmanroberti)).
neg(f(atonygoldwyn,aklischstefan)).
neg(f(achelcieross,asciveresmarianna)).
neg(f(ajurneesmollett,asummereric)).
neg(f(amarisaburger,agustemmanuelii)).
neg(f(alorigalinski,akrgnther)).
neg(f(afrancishuster,acatonjonesmichael)).
neg(f(avincentdonofrio,averhoevenpauli)).
neg(f(aauroraquattrocchi,asummereric)).
neg(f(atommikulla,abattiatofranco)).
neg(f(avannifois,amarinovichanton)).
neg(f(ajackmcgee,apunchevborislav)).
neg(f(aalexandrawinisky,asoderberghsteven)).
neg(f(amichalbajor,akrgnther)).
neg(f(acynthiastevenson,ametcalfestephen)).
neg(f(aguillaumeromain,asurchadzhievstefani)).
neg(f(avannifois,akrgnther)).
neg(f(aalicjajachiewicz,agustemmanuelii)).
neg(f(astefanodionisi,agutjahrrainer)).
neg(f(amikhailmikhajlov,akappesstphane)).
neg(f(arobyndouglass,akappesstphane)).
neg(f(atommikulla,aaltmanroberti)).
neg(f(afranoisechristophe,asurchadzhievstefani)).
neg(f(anormanarmour,akappesstphane)).
neg(f(aandygarcia,akinkelmartin)).
neg(f(afirminerichard,ametcalfestephen)).
neg(f(astefanpetrov,aaltmanroberti)).
neg(f(aantoniettacarbonetti,atraykovatanas)).
neg(f(anormanarmour,asciveresmarianna)).
neg(f(aminianden,atonetticlaudio)).
neg(f(aivangrigorov,ametcalfestephen)).
neg(f(aellenthomas,akinkelmartin)).
neg(f(aemilmarkov,abonnetchristiani)).
neg(f(aneilmaskell,akrgnther)).
neg(f(abradpitt,abraunbettinai)).
neg(f(acoralyzahonero,atraykovatanas)).
neg(f(araffaeladavi,akappesstphane)).
neg(f(alyubomirkanev,aromeclaudemichel)).
neg(f(afrancishuster,amarinovichanton)).
neg(f(akirilyanev,akronthalerthomas)).
neg(f(asaromiano,asoderberghsteven)).
neg(f(atommikulla,amarinovichanton)).
neg(f(alorigalinski,astephanbernhard)).
neg(f(ahristodinev,ametcalfestephen)).
neg(f(arobertculp,aapprederisfranck)).
neg(f(aberniemac,atraykovatanas)).
neg(f(asavahashamov,aengelhardtwilhelm)).
neg(f(asamantharnier,akronthalerthomas)).
neg(f(agiancarloscuderi,akrgnther)).
neg(f(accilecassel,averhoevenpauli)).
neg(f(atzenokandov,agustemmanuelii)).
neg(f(amarcospicuglia,abattiatofranco)).
neg(f(apetardespotov,abattiatofranco)).
neg(f(akostatsonev,akappesstphane)).
neg(f(aanthonyheald,amillergeorgei)).
neg(f(abillcable,asummereric)).
neg(f(adavidsontag,aklischstefan)).
neg(f(arobyndouglass,atonetticlaudio)).
neg(f(apierrearditi,asurchadzhievstefani)).
neg(f(aberniemac,amarinovichanton)).
neg(f(asheilapaterson,asummereric)).
neg(f(aeddasabatini,acatonjonesmichael)).
neg(f(ajannowicki,astephanbernhard)).
neg(f(adillonmoen,atraykovatanas)).
neg(f(adannflorek,aengelhardtwilhelm)).
neg(f(atizianalodato,agustemmanuelii)).
neg(f(aradarassimov,apunchevborislav)).
neg(f(avincentdonofrio,azensmichael)).
neg(f(aloccorbery,acatonjonesmichael)).
neg(f(abarbaratabita,agrimaldiaurelioi)).
neg(f(alyubomirbachvarov,astephanbernhard)).
neg(f(ajustinmonjo,aklischstefan)).
neg(f(aivandimov,agrimaldiaurelioi)).
neg(f(asaromiano,apunchevborislav)).
neg(f(ahubertmulzer,asurchadzhievstefani)).
neg(f(amanueladolcemascolo,astephanbernhard)).
neg(f(anikoladadov,asummereric)).
neg(f(avincentlecoeur,akappesstphane)).
neg(f(adonatellafinocchiaro,astephanbernhard)).
neg(f(aemiliaradeva,aklischstefan)).
neg(f(agusmercurio,agutjahrrainer)).
neg(f(aelliottgould,apakulaalanj)).
neg(f(adinamerrill,amillergeorgei)).
neg(f(anelsonpeltz,akronthalerthomas)).
neg(f(atzvetolyubrakovski,acatonjonesmichael)).
neg(f(apierrearditi,ametcalfestephen)).
neg(f(ajannowicki,abraunbettinai)).
neg(f(aguillaumeromain,akappesstphane)).
neg(f(amanliosgalambro,agutjahrrainer)).
neg(f(acarolflorence,agustemmanuelii)).
neg(f(atimothypaulperez,aaltmanroberti)).
neg(f(astevekalfa,ametcalfestephen)).
neg(f(apenlopecruz,aklischstefan)).
neg(f(aginachiarelli,amillergeorgei)).
neg(f(asydneypollack,abattiatofranco)).
neg(f(aelliottgould,akronthalerthomas)).
neg(f(abillyconnolly,aladogedominique)).
neg(f(aivantonev,asoderberghsteven)).
neg(f(athomasstielner,atraykovatanas)).
neg(f(adenisarndt,apunchevborislav)).
neg(f(ascottcaan,atonetticlaudio)).
neg(f(agesinecukrowski,abonnetchristiani)).
neg(f(aguillaumeromain,apakulaalanj)).
neg(f(aemiliaradeva,azensmichael)).
neg(f(apaullnolan,apunchevborislav)).
neg(f(aantoniettacarbonetti,astephanbernhard)).
neg(f(aginachiarelli,aengelhardtwilhelm)).
neg(f(ajuliedray,abattiatofranco)).
neg(f(aivankondov,agrimaldiaurelioi)).
neg(f(ageorgistamatov,agrimaldiaurelioi)).
neg(f(adidierdijoux,ametcalfestephen)).
neg(f(ajohnfinn,agrimaldiaurelioi)).
neg(f(afranoisechristophe,akrgnther)).
neg(f(asaromiano,aromeclaudemichel)).
neg(f(achelcieross,ametcalfestephen)).
neg(f(aivangrigorov,akrgnther)).
neg(f(atonygoldwyn,agrimaldiaurelioi)).
neg(f(aannamariagherardi,asummereric)).
neg(f(adavidthewlis,aladogedominique)).
neg(f(abenjaminmouton,akappesstphane)).
neg(f(asavahashamov,asummereric)).
neg(f(acaitlinoheaney,asummereric)).
neg(f(agesinecukrowski,asoderberghsteven)).
neg(f(alyubomirkanev,astephanbernhard)).
neg(f(asamshepard,azensmichael)).
neg(f(acorradofortuna,apunchevborislav)).
neg(f(aleonardlansink,apakulaalanj)).
neg(f(amarcospicuglia,atraykovatanas)).
neg(f(ajohnheard,asummereric)).
neg(f(ajuttawachowiak,aaltmanroberti)).
neg(f(avincentlecoeur,aaltmanroberti)).
neg(f(anormanarmour,atonetticlaudio)).
neg(f(acharlotterampling,agrimaldiaurelioi)).
neg(f(acarmelogalati,amarinovichanton)).
neg(f(alyubomirbachvarov,asummereric)).
neg(f(acaseyaffleck,akrgnther)).
neg(f(adavidsontag,akrgnther)).
neg(f(aivantonev,apakulaalanj)).
neg(f(ajeannetripplehorn,aengelhardtwilhelm)).
neg(f(amariashopova,azensmichael)).
neg(f(aalancpeterson,atraykovatanas)).
neg(f(aloccorbery,agrimaldiaurelioi)).
neg(f(ajanchappell,atonetticlaudio)).
neg(f(alewissmith,atraykovatanas)).
neg(f(adinaconnolly,abattiatofranco)).
neg(f(astanleytucci,akronthalerthomas)).
neg(f(araffaeladavi,aapprederisfranck)).
neg(f(amarenschumacher,averhoevenpauli)).
neg(f(avyarakovacheva,agrimaldiaurelioi)).
neg(f(aloccorbery,amarinovichanton)).
neg(f(ajurneesmollett,averhoevenpauli)).
neg(f(aclaudiamessner,apunchevborislav)).
neg(f(adavidthewlis,agrimaldiaurelioi)).
neg(f(alarrysontag,acatonjonesmichael)).
neg(f(astoychomazgalov,akrgnther)).
neg(f(adidierdijoux,abonnetchristiani)).
neg(f(ajannowicki,agustemmanuelii)).
